### PR TITLE
Fixes #2002 sgcollect_info pprof pdf files are empty

### LINKED ISSUE #2002: sgcollect_info pprof pdf files are empty
When testing locally on OSX, I noticed that the heap.pdf file generated is empty.  However, running `go tool pprof` directly generates a non-empty heap.pdf file.

### PR DESCRIPTION
**Pull request by tleyden**
This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/2003)

### CODE REVIEW

**Comment by ajres** [comment]
_[tools/sgcollect_info, line 175 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/2003#-KNcr_89SWBQUpClE5LL:-KNcr_89SWBQUpClE5LM:-860600786) ([raw file](https://github.com/couchbase/sync_gateway/blob/e3639f4d68d378cb88e644d2933168b5faf63c41/tools/sgcollect_info#L175)):_

> ```
>                 description,
>                 cmd,
>                 log_file=dest_path,
> ```

dest_path is being used here, but it is no longer used to write the pprof output to disk, is it redundant, do the populated reports end up in the .ZIP?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2003)_

**Comment by tleyden** [comment]
> dest_path is being used here, but it is no longer used to write the pprof output to disk, is it redundant

I put more info on https://github.com/couchbase/sync_gateway/issues/2002

So `go tool pprof` is writing to stdout now, and sgcollectinfo is taking care to redirect that to log_file.

> do the populated reports end up in the .ZIP?

They do on my machine!  Would be great if you could test on your end as well.

**Comment by tleyden** [comment]
> do the populated reports end up in the .ZIP?

Just tested on linux and the heap.pdf was correctly generated and added to the zip.

**Comment by ajres** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2003#-:-KNd-p6ZD_BA8ENiOqB7:1417088721)_

**Comment by ajres** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2003)_

**Pull request merged**
