### PR TITLE
Fixes #2028 sg-collect-info can check in known places for Sync Gatewa…

### LINKED ISSUE #2028: sg-collect-info can check in known places for Sync Gateway binary
When testing under Docker in https://github.com/couchbase/sync_gateway/issues/2027, the sync gateway binary was missing from the sgcollectinfo output.

Currently it only checks the expvars and the user provided command line option.  It could also check from a list of well known paths, which would increase the chances of collecting it.

### PR DESCRIPTION
**Pull request by tleyden**
…y binary

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/2052)

### CODE REVIEW

**Comment by ajres** [comment]
_[tools/sgcollect_info, line 465 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/2052#-KPxk_e-uIQV841hCjA6:-KPxk_e-uIQV841hCjA7:bidgzi5) ([raw file](https://github.com/couchbase/sync_gateway/blob/4f9ab4bfa8c6a3d8eeac1377cb7b63657b446f5a/tools/sgcollect_info#L465)):_

> ```
> 
> 
>     # Collect the SG binary
> ```

Is this comment correct in this context, we don't appear to collect the binary here?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2052)_

**Comment by tleyden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[tools/sgcollect_info, line 465 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/2052#-KPxk_e-uIQV841hCjA6:-KPxpep1REvDJJ6m-hAx:b-wfh43) ([raw file](https://github.com/couchbase/sync_gateway/blob/4f9ab4bfa8c6a3d8eeac1377cb7b63657b446f5a/tools/sgcollect_info#L465)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> Is this comment correct in this context, we don't appear to collect the binary here?
> </details>
> Good catch.  Fixed in latest commit on this branch.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2052)_

**Comment by ajres** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2052#-:-KQ-TAriC1E4g3HeKoFZ:bnfp4nl)_

**Comment by ajres** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2052)_

**Pull request merged**
