### PR TITLE
#3551 Show server pool UUID in GET /{db}

### LINKED ISSUE #3551: Store Couchbase Server pool UUID per-database in sgcollect_info
Fetching the Couchbase Server pool/cluster UUID per-database as part of sgcollect_info will allow support tooling to automatically link collections of couchbase server and sync gateway.

The pool UUID can be retrieved via the REST API at `GET /pools` under the key `uuid`. This endpoint requires authentication.

### PR DESCRIPTION
**Pull request by bbrks**
Fixes #3551 

- Lazily loads server UUID in `GET /{db}` when using a `GoCBBucket`
- All other bucket types (e.g. Walrus) do not show a `server_uuid` entry in the response
- Copied `mgmtRequest` from GoCB when calling Couchbase Server's REST API

## Integration Tests
- [x] http://uberjenkins.sc.couchbase.com/job/sync-gateway-integration-master/836/

### CODE REVIEW

**Comment by JFlath** [comment]
It's really bikeshed-y, but I'm on the fence about the naming of this. Whilst it does come from the `pools` API and the `default` pool, pools in general are a kind of strange concept seeing as we basically only expect this to be `default`. In other places, we use this as the de facto Cluster UUID and I think maybe that would be a clearer name... I won't be heartbroken if it stays as-is, just mentioning :)

**Comment by adamcfraser** [comment]
I agree with @JFlath about the naming - looking back at the API endpoint, the UUID being returned isn't associated with a specific pool (leaving aside the fact that server only ever runs with the default pool anyway).  I'd prefer server UUID over cluster UUID, since it's being returned from SG's db endpoint, and there would be some ambiguity about whether that refers to the SG cluster or the CBS cluster.

**Comment by JFlath** [comment]
Sorry, bikeshedding again, I should have spoken up sooner! I agree that ClusterUUID would be misleading (as it might refer to a Sync Gateway Cluster) of some sort, but equally this isn't the UUID for the (Couchbase) Server, it's the UUID for the Couchbase Server *Cluster*, and the fact that it's for the whole cluster is a key point. Maybe `BackingClusterUUID`?

Honestly, again, I won't be heartbroken if it stays as is...

**Comment by bbrks** [comment]
I agree that the term "server" can be misleading or ambiguous when thinking of individual nodes. But also note that we pretty consistently use "server" elsewhere to mean "Couchbase Server", i.e. a cluster, rather than a single node. Take `db.server` from the config for instance.

**Review by adamcfraser — APPROVED** [review]

**Pull request merged**
