### PR TITLE
Optimize view and design doc usage

### PR DESCRIPTION
**Pull request by adamcfraser**
View engine team suggests that there are decreasing performance benefits when using more than 4 design docs - the performance overhead to add the additional DCP streams on the view index nodes outweighs the benefits seen by concurrent indexing.

Also removes the on-startup view query related to user warnings.

### CODE REVIEW

**Comment by tleyden** [comment]
Tests in progress

- http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/212/
http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/213/

**Review by tleyden — CHANGES_REQUESTED** [review]
Once unit integration tests pass, can be merged.  They're in progress.

**Comment by adamcfraser** [comment]
Haven't yet been able to repro the error in http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/213/ locally - need to retry against 4.x database.

**Comment by adamcfraser** [comment]
Test failure highlights (existing) missed error check in putDesignDoc.  Added error handling and resubmitted job, may get better diagnostics on failure. 

Rerunning as http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/215/

**Comment by adamcfraser** [comment]
Integration tests ran clean in http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/215/ (which was rerun of #213).

**Comment by adamcfraser** [comment]
Merging based on latest clean integration test runs - previous error in #213 didn't look related to this change.  If error from #213 resurfaces we should at least have better diagnostics at that point.

**Pull request merged**
