### PR TITLE
asciidoc docs

### PR DESCRIPTION
**Pull request by jamesnocentini**
This is a pandoc conversion from https://developer.couchbase.com/documentation/mobile/2.0/installation/sync-gateway/index.html

### CODE REVIEW

**Review by tleyden — APPROVED** [review]
LGTM

**Review by bbrks — APPROVED** [review]

**Comment by tleyden** [comment]
@jamiltz does this need to be on master?  or would it be ok on the `dev` branch?  

Currently, master is reserved for the 2.0.0 release and we're trying to keep commits here to a minimum.

**Comment by jamesnocentini** [comment]
Yes `dev` is fine.

**Comment by jamesnocentini** [comment]
@adamcfraser awaiting your approval. Please merge unless you have any questions of course.

@tleyden @bbrks FYI on the next PR I'll assign only 1 person to review and merge the PR. I assigned everyone on this one because I wasn't sure about which base branch to use and the process etc.

**Pull request merged**
