### PR TITLE
Fixes #2055 Functional test failing: Test Openidconnect Negative Toke…

### LINKED ISSUE #2055: Functional test failing: Test Openidconnect Negative Token Expiry
I noticed this in https://github.com/couchbaselabs/mobile-testkit/pull/649 and it appears to be a clear regression from 1.3.0.

To reproduce using mobile-testkit:

```
robot -b debug.txt -v SERVER_VERSION:4.1.1 -v SYNC_GATEWAY_VERSION:96e6e4927dfd648b153022b2f83665a967445167 -t "Test Openidconnect Negative Token Expiry" testsuites/syncgateway/functional/1sg_1cbs/
```

This gives the test failure error:

```

KEYWORD test_openid_connect . Test Openidconnect Negative Token Expiry sg_url=${sg_url}, sg_db=${sg_db}
Start / End / Elapsed:  20160824 15:00:25.192 / 20160824 15:00:25.724 / 00:00:00.532
15:00:25.193    DEBUG   Test timeout 10 minutes active. 585.072 seconds left.   
15:00:25.193    INFO    Invoking _oidc_challenge against: http://s61803cnt72.sc.couchbase.com:4984/db/_oidc_challenge?provider=test 
15:00:25.195    INFO    Starting new HTTP connection (1): s61803cnt72.sc.couchbase.com  
15:00:25.501    DEBUG   "GET /db/_oidc_challenge?provider=test HTTP/1.1" 401 50 
15:00:25.503    INFO    Starting new HTTP connection (1): s61803cnt72.sc.couchbase.com  
15:00:25.506    DEBUG   "GET /db/_oidc_testing/authorize?client_id=sync_gateway&redirect_uri=http%3A%2F%2Fs61803cnt72.sc.couchbase.com%3A4984%2Fdb%2F_oidc_callback&response_type=code&scope=openid+email&state= HTTP/1.1" 200 1632 
15:00:25.508    INFO    Starting new HTTP connection (1): s61803cnt72.sc.couchbase.com  
15:00:25.510    DEBUG   "POST /db/_oidc_testing/authenticate?client_id=sync_gateway&redirect_uri=http%3A%2F%2Fs61803cnt72.sc.couchbase.com%3A4984%2Fdb%2F_oidc_callback&response_type=code&scope=openid+email&state= HTTP/1.1" 302 0    
15:00:25.723    DEBUG   "GET /db/_oidc_callback?code=dGVzdHVzZXI%3D&state=af0ifjsldkj HTTP/1.1" 400 63  
15:00:25.724    FAIL    AssertionError  
15:00:25.724    DEBUG   Traceback (most recent call last):
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/testsuites/syncgateway/functional/test_openid_connect.py", line 314, in test_openidconnect_negative_token_expiry
    assert response.status_code == 500
```

But switching to SG 1.3.0 (commit on 1.3 tag 8c3ee28ae746b1e4a5a98e5df3b890d2f6a559e0) the problem goes away:

```
$ robot -b debug.txt -v SERVER_VERSION:4.1.1 -v SYNC_GATEWAY_VERSION:8c3ee28ae746b1e4a5a98e5df3b890d2f6a559e0 -t "Test Openidconnect Negative Token Expiry" testsuites/syncgateway/functional/1sg_1cbs/
...
Test OpenIDConnect Negative Token Expiry :: Create a token with a ... | PASS |
------------------------------------------------------------------------------
1Sg 1Cbs.1Sg 1Cbs-Openid-Connect                                      | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
```

### PR DESCRIPTION
**Pull request by tleyden**
…n Expiry

Fixes #2055

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/2056)

### CODE REVIEW

**Comment by tleyden** [comment]
There's a tool called `errcheck` which might have caught this:

http://dominik.honnef.co/posts/2014/12/go-tools/

## errcheck

Install with go get github.com/kisielk/errcheck
Ignoring errors in Go is more difficult than ignoring exceptions in some other languages, but it’s not impossible. Some people even say that it’s way too easy. Call a function like (*os.File).Close without looking at its return value, and that’s an error gone by unnoticed.

The errcheck tool has been written to help you find exactly those function calls. Running errcheck on a package will report all function calls that have unchecked errors.

The following code has three unchecked errors, one for each method call:

```
package main

import "os"

func main() {
    f, _ := os.Open("foo")
    f.Write([]byte("Hello, world."))
    f.Close()
}
```

Running errcheck with the default options on it will produce the following output:

```
foo/foo.go:7:9  f.Write([]byte("Hello, world."))
foo/foo.go:8:9  f.Close()
```

Do note that it is not printing the call to os.Open – that’s because assignment to _ is not interpreted as “unchecked” by default. That’s because assigning errors to _ can be a valid pattern, for when one truly doesn’t care about an error, or because it’s known that an error cannot occur (that’s true for some implementations of the io.Writer interface, for example). If you do worry about someone assigning to _ out of laziness, you can run errcheck with the -blank flag:

```
foo/foo.go:6:5  f, _ := os.Open("foo")
foo/foo.go:7:9  f.Write([]byte("Hello, world."))
foo/foo.go:8:9  f.Close()
```

Furthermore, errcheck comes with options for ignoring certain packages or functions, to avoid false positives. Together with go vet, it should be part of your quality assurance scripts

**Comment by tleyden** [comment]
Jenkins run in progress: http://uberjenkins.sc.couchbase.com/view/QE%20Dev/job/syncgateway-functional-tests-dev/138/

**Comment by tleyden** [comment]
Jenkins result

```
21:14:28 ------------------------------------------------------------------------------
21:14:28 1Sg 1Cbs.1Sg 1Cbs-Openid-Connect                                      | PASS |
21:14:28 1 critical test, 1 passed, 0 failed
21:14:28 1 test total, 1 passed, 0 failed
21:14:28 ==============================================================================
```

**Comment by tleyden** [comment]
@ajres / @adamcfraser -- this should be ready to merge

**Comment by adamcfraser** [comment]
@tleyden Thanks for catching and fixing this - the fix looks good to me.

**Pull request merged**
