### PR TITLE
Do we still need this file for anything?

### PR DESCRIPTION
**Pull request by tleyden**

### CODE REVIEW

**Comment by tleyden** [comment]
@snej since you added this file, let us know if you still need it for anything.  @adamcfraser wants to merge to coordinate w/ release tag timing

**Comment by snej** [comment]
It's for the TextMate editor; it configures things like which files/dirs to show. I haven't used TextMate to edit SG in years, and I don't know if anyone else does. If the file hasn't been updated recently, it'll be out of date anyway, so I say get rid of it.

**Comment by snej** [comment]
…actually on reading the file, I see that it just has stuff like a file-type mapping and tab settings. Seems handy to have if anyone uses TextMate. It's a hidden file, so is there harm in keeping it?

**Comment by tleyden** [comment]
We discussed this in a sprint planning meeting and decided to remove it for now, but re-add it when we have users using textmate.  If nobody is keeping the file up to date, it might throw off users

**Pull request merged**
