### PR TITLE
Ignore IntelliJ project files and Windows service wrapper

### PR DESCRIPTION
**Pull request by zgramana**
- Adds a Windows service wrapper for `sg_accel.exe`.
- Fixes an issue in both service wrappers where the wrapper service reports it's running despite a failure to start `sync_gateway.exe` or `sg_accel.exe`.
- Small whitespace formatting improvements.
- `.gitignore` updates to ignore IntelliJ project files and intermediate builds.

### CODE REVIEW

**Comment by adamcfraser** [comment]
@zgramana Were the new submodule commits under /vendor added accidentally?

**Comment by zgramana** [comment]
Gar, yes. A tool I had open kept automatically adding them in. Thought that I had finally gotten past it, but they appear to have slipped back in. I'll get them removed this morning.

**Comment by zgramana** [comment]
@adamcfraser vendor'ed submodules are now removed.

**Comment by tleyden** [comment]
Looks good, can you squash this into a single commit?

**Comment by zgramana** [comment]
@tleyden done!

**Pull request merged**
