### PR TITLE
Improvements to  feed latency handling

### PR DESCRIPTION
**Pull request by adamcfraser**
The Couchbase Server TAP and DCP feeds don't guarantee sequential delivery of updates.  Sync Gateway previously buffered these updates to rebuild the changes in sequence order (needed for replication). When an entry on the feed was very slow, it led to several problems:
- After a timeout period, that sequence was skipped.  Even if it later appeared in the feed, clients wouldn't know to retrieve it
- If the timeout is extended (as it recently was to 60s), the changes feed will go silent until that timeout is reached

This commit implements an alternate approach:
- After a shorter timeout, late sequences are skipped, but tracked by the change cache in `skippedSeqs`
- When there are entries in the skippedSeqs, sequence numbers are sent to the client in the form lowSequence::sequence, where lowSequence is the lowest contiguous sequence for the gateway (skippedSeqs[0] - 1).   Subsequent client requests that include a lowSequence in the since value will retrieve from the lowSequence value.
- A periodic cleanup function abandons values that have been in the skippedSeqs queue (default time for removal from skipped Seqs is 60 minutes).

For continuous changes feeds, late-arriving (previously skipped) sequences are sent in each iteration of the continuous changes loop.  Each channel cache maintains a history of late-arriving sequences for use by continuous changes feeds to support this functionality.

Includes support for customization of sequence handling settings (pending timeout, skipped timeout, max pending) via the database config.

### CODE REVIEW

**Comment by adamcfraser** [comment]
Design notes on the implementation here: https://github.com/adamcfraser/cbnotes/wiki/Handling-Sequence-Latency

**Comment by jchris** [comment]
Looks great. My only confusion is about max_num_pending -- I think I see
why it is in there (to set an upper bound to the missing cache?) but I'm
having trouble imagining its boundary conditions. Should exceeding this
number result in a hard panic, to signal to downstream listeners that
something went out of bounds? Or can the error be handled softer?

Actually maybe I get it now, looking at what happens when something falls
out of pending, it goes into missed. Is there a max size for the missed
list?

On Tuesday, February 3, 2015, Adam Fraser notifications@github.com wrote:

> Design notes on the implementation here:
> https://github.com/adamcfraser/cbnotes/wiki/Handling-Sequence-Latency
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/couchbase/sync_gateway/pull/624#issuecomment-72769914
> .

## 

Chris Anderson  @jchris
http://www.couchbase.com

**Comment by adamcfraser** [comment]
You're right about max_num_pending - it's just exposing the pre-existing functionality of the sequence buffering.  The missed sequence handling has overhead associated with it, so I didn't think it was a good idea to move to zero-buffering (where every out-of-sequence entry would go to missed immediately).  The max_num_pending and max_wait_pending settings are used for that buffering.

Right now there's no size limit on the missed queue - sequences only get abandoned when the max_wait is exceeded.  I assumed that even if we hit a period of high load that generated a lot of entries to missed, we still didn't want to start abandoning missed sequences, but let me know if you disagree.

**Comment by jchris** [comment]
I agree. My question becomes: what are the correctness implications of the
missed queue length going to infinity?

I think it would be ok, just want to think through the edge cases.

On Wednesday, February 4, 2015, Adam Fraser notifications@github.com
wrote:

> You're right about max_num_pending - it's just exposing the pre-existing
> functionality of the sequence buffering. The missed sequence handling has
> overhead associated with it, so I didn't think it was a good idea to move
> to zero-buffering (where every out-of-sequence entry would go to missed
> immediately). The max_num_pending and max_wait_pending settings are used
> for that buffering.
> 
> Right now there's no size limit on the missed queue - sequences only get
> abandoned when the max_wait is exceeded. I assumed that even if we hit a
> period of high load that generated a lot of entries to missed, we still
> didn't want to start abandoning missed sequences, but let me know if you
> disagree.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/couchbase/sync_gateway/pull/624#issuecomment-72898035
> .

## 

Chris Anderson
http://www.couchbase.com
http://twitter.com/jchris
"Compromising before you even begin fighting is illogical." – Joshua Wong

**Comment by tleyden** [comment]
@adamcfraser in case you don't already know about it, the unit tests seem to currently be failing:

```
$ ./test.sh
?       github.com/couchbaselabs/sync_gateway   [no test files]
# github.com/couchbaselabs/sync_gateway/db
db/attachment_test.go:36: not enough arguments in call to NewDatabaseContext
db/change_cache_test.go:70: not enough arguments in call to NewDatabaseContext
db/database_test.go:47: not enough arguments in call to NewDatabaseContext
db/database_test.go:667: not enough arguments in call to NewDatabaseContext
ok      github.com/couchbaselabs/sync_gateway/auth  2.081s
ok      github.com/couchbaselabs/sync_gateway/base  0.040s
ok      github.com/couchbaselabs/sync_gateway/channels  0.158s
FAIL    github.com/couchbaselabs/sync_gateway/db [build failed]
ok      github.com/couchbaselabs/sync_gateway/rest  7.748s
```

**Comment by tleyden** [comment]
I'm migrating a few comments from #617 since they are specific to this PR.

**Comment by tleyden** [comment]
In [perf run 645](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/645), which is running against the **feature/issue_525_instrumented** branch, it has currently exceeded [1 million](https://gist.github.com/tleyden/4a827a1130c1215ce253#file-gistfile1-txt-L109) goroutines.

This corresponds with the previous observation that the function responsible for the most heap allocation was shown to be [newproc_m](https://gist.github.com/tleyden/a4398685e784e86f3063#file-gistfile1-txt-L8)

I have another perf run scheduled against the master branch to compare the number of goroutines being spawned.

**Comment by tleyden** [comment]
In [perf run 647](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/647/), I was able to manually cause the sync gateway process to dump its goroutines towards the end of the run by running `kill -s SIGQUIT <sync_gw_pid>`

I think only a portion of the goroutine stacks were captured in the [sync gateway logs](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/647/artifact/gateway.log_1.gz) for that run, but hopefully its enough to go on for now. 

I took a snippet from the top and bottom of the logs and put them in a [gist](https://gist.github.com/tleyden/d47eb9e03937ae8ffe9f) for easy viewing.

Towards the second half of the gist, there are many repeated entries that look like this:

```
goroutine 1909554 [semacquire, 37 minutes]:
sync.(*Mutex).Lock(0xc2081c6158)
    /usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc2081c6158)
    /usr/local/go/src/sync/rwmutex.go:82 +0x33
github.com/couchbaselabs/sync_gateway/db.(*changeCache).processEntry(0xc2081c60d0, 0xc238400a80, 0x0)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go:359 +0x55
github.com/couchbaselabs/sync_gateway/db.func·005()
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go:320 +0xb6e
created by github.com/couchbaselabs/sync_gateway/db.(*changeCache).DocChanged
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go:324 +0x1b0

```

**Comment by tleyden** [comment]
In [perf run 649](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/649/), which was against the master branch, the max # of goroutines I saw in expvars was approx 40K.

I ran `SIGQUIT` against a live process towards the end of the run, and the goroutine stacktraces were captured in this gzipped log file:

http://cl.ly/1G331o412h3b?_ga=1.89479000.257213425.1401744125

It killed the process, which is why the job has no artifacts attached.

**Comment by tleyden** [comment]
In [perfrun 673](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/673/), here's a [snapshot of the lock instrumentation](https://gist.github.com/tleyden/c046b1d28af771528457#file-gistfile1-txt-L342)

Note:
- the [single open lock on lock-getChannelCache](https://gist.github.com/tleyden/c046b1d28af771528457#file-gistfile1-txt-L1728)
- the [plethora of locks on lateseqlock-multichangesfeed](https://gist.github.com/tleyden/c046b1d28af771528457#file-gistfile1-txt-L1714-L1726)

The corresponding code in the **feature/issue_525_isync** branch that names these locks is here:
- [change_cache.go#L499](https://github.com/couchbase/sync_gateway/blob/feature/issue_525_isync/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go#L499)
- [changes.go#L218](https://github.com/couchbase/sync_gateway/blob/feature/issue_525_isync/src/github.com/couchbaselabs/sync_gateway/db/changes.go#L218)

**Comment by adamcfraser** [comment]
Moved to #686.

**Pull request closed without merging**
