### PR TITLE
Refactor event.Sequence -> event.Cas

### PR DESCRIPTION
**Pull request by tleyden**
Fixes https://github.com/couchbase/sg-bucket/issues/35

- [x] Merge https://github.com/couchbase/sg-bucket/pull/36
- [x] Merge https://github.com/couchbaselabs/walrus/pull/36
- [x] Update manifest

### CODE REVIEW

**Review by bbrks — APPROVED** [review]
LGTM

**Review by adamcfraser — COMMENTED** [review]
Looks good to me.  Manifest may need to be updated after walrus/sg-bucket branches are merged.

**Comment by tleyden** [comment]
Ok I'll get those companion PR's up.

**Comment by adamcfraser** [comment]
Dependent PRs are merged - ready for manifest update

**Pull request merged**
