### PR TITLE
Add RenderGraphvizDot()

### PR DESCRIPTION
**Pull request by tleyden**
This was particularly useful when writing unit tests for https://github.com/couchbase/sync_gateway/issues/2651

Example generated diagram:

three_branches

### CODE REVIEW

**Comment by tleyden** [comment]
I added a REST endpoint `_revtree` to the admin REST API.  Example usage:

```
$ curl -v -X GET \
>   http://localhost:4985/db/_revtree/17cc52b86f3f7d4cf3c9d31d6478a060 \
>   -H 'authorization: Basic Zm9vOmZvbw==' \
>   -H 'cache-control: no-cache' \
>   -H 'content-type: application/json' \
>   -H 'postman-token: 3c1865aa-b1ce-6ebb-4602-fa44b2f7e58a' \
>   -d '{
>   "key": "val"
> }'
*   Trying ::1...
* connect to ::1 port 4985 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4985 (#0)
> GET /db/_revtree/17cc52b86f3f7d4cf3c9d31d6478a060 HTTP/1.1
> Host: localhost:4985
> User-Agent: curl/7.43.0
> Accept: */*
> authorization: Basic Zm9vOmZvbw==
> cache-control: no-cache
> content-type: application/json
> postman-token: 3c1865aa-b1ce-6ebb-4602-fa44b2f7e58a
> Content-Length: 18
>
* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 200 OK
< Content-Length: 97
< Content-Type: text/plain charset=utf-8
< Server: /1.5 branch/ commit/
< Date: Thu, 22 Jun 2017 22:30:30 GMT
<
* Connection #0 to host localhost left intact
digraph graphname{"1-ecbd22495c41163e3657699fd1f5ca28" -> "2-9751b0b11d5cbeae6d9d756603b4cdc2"; }
```

**Review by adamcfraser — APPROVED** [review]
Looks great.

**Comment by JFlath** [comment]
I'm pretty worried about putting this into the product and documenting it (https://github.com/couchbaselabs/couchbase-mobile-portal/issues/750) - is this a supported feature now? We've identified issues where it was used in https://github.com/couchbase/sync_gateway/issues/2651 - have these been fixed?

I want to make sure we don't end up in the same position as the UI...

**Comment by jamiltz** [comment]
Good points, I'll defer to @tleyden and @ssmotra.

**Comment by tleyden** [comment]
@jflath The issues in #2651 weren't related to the _revtree endpoint.

We definitely need this endpoint since it's potentially a huge debugging time saver.  And it needs to be documented because folks that are debugging shouldn't be forced to dig into code. 

What about adding a disclaimer to the api docs stating that this endpoint is not officially supported?

**Comment by JFlath** [comment]
@tleyden The point I was referring to was:

>I think it's safe to ignore that empty node, it's most likely just a bug in the graphviz dot export

---

I think marking it as unsupported is fine - was this originally the plan?

**Comment by tleyden** [comment]
Oh yeah, that's an outstanding bug and I was planning to live with it rather than fix it.

I don't think there was originally any plan to mark it as unsupported.  I filed a docs issue here: https://github.com/couchbaselabs/couchbase-mobile-portal/issues/758

**Pull request merged**
