### PR TITLE
Parse sync function (and wrapper) only once

### PR DESCRIPTION
**Pull request by pritambaral**
The function returned by evaluating `funcSource` is called for every document update. The old function included the declarations of all helper function (`makeArray`, `requireUser` etc.) and the sync function. Thus, on every document update, all such functions are parsed all over again.

Steps to reproduce:

(Note [sync_runner.go#L26](https://github.com/couchbase/sync_gateway/blob/443be965f30e092307cbcfb9ae866e1fe0f82558/src/github.com/couchbase/sync_gateway/channels/sync_runner.go#L26) first)
1. Use the following as sync function in config:

```
"sync": `1; var a = v; v = function(d,o) {console.log("document:", d, "a:", a++);}`
```
1. Create/make two updates to any document.

Expected output:

```
document: [object Object] a: 1
document: [object Object] a: 2
```

Actual output:

```
document: [object Object] a: 1
document: [object Object] a: 1
```

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1579)

### CODE REVIEW

**Comment by ajres** [comment]
Thanks for the contribution @pritambaral! 

Before we can accept PR's we need you to sign our [contributors license agreement](http://review.couchbase.org/#/settings/agreements).

**Comment by pritambaral** [comment]
@ajres I can't sign in at the provided. Only yahoo accounts seem to be allowed, and I don't have one.
Did you mean http://review.couchbase.org ?

PS: This is not mentioned in [CONTRIBUTING.md](https://github.com/couchbase/sync_gateway/blob/5a247b0/CONTRIBUTING.md) either

**Comment by pritambaral** [comment]
Registering via that link too requires a Yahoo account.

Can't I just register with my email or Github account?

**Comment by adamcfraser** [comment]
@pritambaral A few questions on this PR:
1. Have you done any benchmarking to identify the benefit of making this change?  At a high level it seems reasonable but I'm not sure what the actual runtime difference would be, given that the raw source is getting parsed and converted to an in-memory javascript object before being used.
2. I think we'd need some unit tests included to validate that there's no change in the stateless behaviour of things like requireUser, requireAccess, etc.  Again - it looks reasonable based on a visual review of the code, but would want that validation included before we could merge.

**Comment by pritambaral** [comment]
@adamcfraser
1. Are there any existing benches I can run? I don't want to benchmark just the execution of the sync function (i.e., 'parse and exec' vs 'exec') because that wouldn't be indicative of real world usage, on the one hand ... and on the other, I'm sure compared to everything else that goes on, parsing time is minimal. This just seemed like such an obvious waste of cycles.
2. Will look into writing tests to prove statelessness of helper functions. I suppose the helpers need to be stateless across calls to the sync function itself, and not beyond that. In other words, I'm only going to be testing multiple calls to the sync function with varying `realUserCtx`

**Comment by pritambaral** [comment]
@adamcfraser Tests added.

**Comment by zgramana** [comment]
@ajres please add some profiling to see the performance overhead. Please also add in some longer, more complicated sync functions to capture an upper range.

**Comment by zgramana** [comment]
Also need to take into account memory pressure differences as well.

**Comment by ajres** [comment]
Validate that _underscore is only setup once in otto and not appended to JS function each run.

**Comment by ajres** [comment]
Test this as a perf scenario using sgload with a complex Sync function and with a large number of doc revisions.

**Comment by ajres** [comment]
This change has been incorporated into PR #2795.

Closing this PR.

**Pull request closed without merging**
