### PR TITLE
Fixes #1851 When sending notauthenticated, it returns a 400 status ra…

### LINKED ISSUE #1851: When sending notauthenticated, it returns a 400 status rather than expected 401
When sending `notauthenticated`, it returns a `400` status rather than `401` — here’s the full ngrep output from a test run: https://gist.github.com/tleyden/321ed59625d96d05b54a9e136e026532

From @adamcfraser:

> When the OP returns an error, I think we should turn that into a 401.  Definitely here:
> https://github.com/couchbase/sync_gateway/blob/feature/issue_1688/rest/oidc_api.go#L106
> 
> I'm less sure about here: https://github.com/couchbase/sync_gateway/blob/feature/issue_1688/rest/oidc_api.go#L111

### PR DESCRIPTION
**Pull request by tleyden**
…ther than expected 401

Previously failing functional test now passes

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1874)

### CODE REVIEW

**Comment by adamcfraser** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[rest/oidc_api.go, line 114 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1874#-KKG1FoobYRO43KA6ux5:-KKG1FoobYRO43KA6ux6:742340920) ([raw file](https://github.com/couchbase/sync_gateway/blob/0dc9ead48b07c53881dee820c707bff59333bfe4/rest/oidc_api.go#L114)):_

> ``` Go
>   code := h.getQuery("code")
>   if code == "" {
>       return base.HTTPErrorf(http.StatusUnauthorized, "Code must be present on oidc callback")
> ```

This and the subsequent request are actually bad requests, and unrelated to whether the user is authorized, in my opinion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1874)_

**Comment by ajres** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1874)_

**Comment by tleyden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[rest/oidc_api.go, line 114 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1874#-KKG1FoobYRO43KA6ux5:-KKLD1VtYdN2_cPYI8_U:-45989496) ([raw file](https://github.com/couchbase/sync_gateway/blob/0dc9ead48b07c53881dee820c707bff59333bfe4/rest/oidc_api.go#L114)):_
<details><summary>

<i>Previously, adamcfraser (Adam Fraser) wrote…</i></summary>



> This and the subsequent request are actually bad requests, and unrelated to whether the user is authorized, in my opinion.
> </details>
> Ok I pushed up a new version that fixes these

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1874)_

**Comment by adamcfraser** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1874)_

**Pull request merged**
