### PR TITLE
Changed retriever URL to reference couchbase repo instead of couchbaselabs repo

### PR DESCRIPTION
**Pull request by ajres**
relates to #682

### CODE REVIEW

**Comment by tleyden** [comment]
Hmm, I just noticed in sg 1.2, it was pointing to

```
[submodule "src/github.com/couchbaselabs/retriever"]
    path = src/github.com/couchbaselabs/retriever
    url = https://github.com/couchbaselabs/retriever
```

https://github.com/couchbase/sync_gateway/blob/1.2.0/.gitmodules#L28-L30

**Comment by ajres** [comment]
But that repo does not exist any more, it's now located in the couchbase repo

**Comment by tleyden** [comment]
It still exists: https://github.com/couchbaselabs/retriever

**Comment by tleyden** [comment]
ok, so it's a redirect :)  now it makes sense why the builds were working

**Comment by tleyden** [comment]
I see you bumped the sha up to the latest commit .. but I think we should use the previous sha:

https://github.com/couchbase/retriever/commit/19c5a5d92a2f34fb96ae91d26901e4a7076b8020

**Comment by tleyden** [comment]
At some point we'll bump all of our sha's up to more recent ones and pair it with a functional/perf testing effort to validate it

**Comment by ajres** [comment]
I reverted the retriever revision

**Comment by tleyden** [comment]
Looks like there was a [unit test failure](http://drone.couchbasemobile.com/couchbase/sync_gateway/9):

```
2016-02-18T21:14:12.305Z HTTP:  #1136: GET http://localhost/db/  (ADMIN)

    admin_api_test.go:772
    assert.True(t, body["state"].(string) == "Online")  
--- FAIL: TestDBOnlineConcurrent (0.10s)
    assert.go:31: 
2016/02/18 21:14:12 Taking DB offline
```

**Comment by tleyden** [comment]
Re-ran build and it passed:

http://drone.couchbasemobile.com/couchbase/sync_gateway/11

**Pull request merged**
