### PR TITLE
Feature/merge dev to master

### PR DESCRIPTION
**Pull request by tleyden**
Merge the dev branch into master

### CODE REVIEW

**Comment by tleyden** [comment]
Integration tests:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/472/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/473/

**Comment by tleyden** [comment]
Seeing integration test failures:

```
2018-04-05T09:29:54.606-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"

	bucket_n1ql_test.go:45
	assert.Equals(t, state, "online")	

	expected: "online"
	     got: &base.IndexMetadata{State:"online"}
--- FAIL: TestN1qlQuery (3.77s)
	assert.go:31: 
2018-04-05T09:29:56.710-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2018-04-05T09:29:58.494-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
2018-04-05T09:30:00.643-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2018-04-05T09:30:02.695-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
--- FAIL: TestMalformedN1qlQuery (5.62s)
	bucket_n1ql_test.go:164: Error creating index: [4300] The index testIndex_value already exists.
```

**Comment by tleyden** [comment]
I'm getting the same error running `func TestN1qlQuery(t *testing.T) {
` locally:

```
2018-04-05T09:34:33.498-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://couchbase-server:8091> as user "test_data_bucket"

	bucket_n1ql_test.go:45
	assert.Equals(t, state, "online")	

	expected: "online"
	     got: &base.IndexMetadata{State:"online"}
	assert.go:31: 
```

**Comment by tleyden** [comment]
Fixed `TestN1qlQuery` in efd60c4e1bdf335f9951bb72c421245a4a72c6e5

**Comment by tleyden** [comment]
More failing index related tests in http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/472/console:

--- FAIL: TestPostUpgradeIndexesSimple (12.81s)
--- FAIL: TestPostUpgradeIndexesVersionChange (0.00s)
--- FAIL: TestNoPanicInvalidUpdate (12.15s)

**Comment by adamcfraser** [comment]
@tleyden The latter errors look like they may be related to Vulcan server enhancements - we probably need to update the CBS used by the integration tests.

**Comment by tleyden** [comment]
Re-running integration tests against CBS 5.5:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/477/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/478/

**Review by adamcfraser — APPROVED** [review]

**Pull request merged**
