### PR TITLE
Fixes #2836 - unit test code coverage

### LINKED ISSUE #2836: Unit test code coverage
Need to measure code coverage of our unit tests.

- [ ] Update unit integration to have a flag (generate coverage report)
- [ ] Attach coverage report to results
- [ ] HTML report

## Options

- [ ] Run tests + coverage in single-pass by using gocoverutil exclusively
- [ ] Currently Walrus and Non-Xattr only -- doesn't do XATTR vs Non-Xattr or Couchbase vs Walrus

## Nice to have

- [ ] Adding stats to PR (requires build machine change)

Possibly move to separate ticket

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #2836

- [x] Update unit integration to have a flag (generate coverage report)
- [x] Attach HTML coverage report to results for SG + SGA
- [x] Attach coverage aggregation tool output to job

## Changes in this PR:

- Consolidates `test.sh` and `test_integration.sh` into single script
- `test.sh` now takes CLI args to customize the behavior with respect to running unit tests vs unit integration tests, as well as optionally generating code coverage reports in either case
- `test.sh` propagates any CLI args after a `--` to the underlying `go tool` or `gocoverutil` command

Example Jenkins run: http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/15/

## Jenkins changes needed post-merge

- Replace [unit integration jenkins job](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/) with config/script from http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage
- Remove http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage

### CODE REVIEW

**Comment by adamcfraser** [comment]
I see a couple of relatively significant gaps in the current jenkins output:

1. I saw the command line output that's been added, but there's still no overall coverage number.  The numbers for the particular packages in that output don't seem particularly useful, as they are giving coverage percentages for the full set of packages based on the tests in each individual package - we'd have to move all tests to a single package to get the aggregate number.
2. Much of the accel-related code that's used by both SG and SGA gets tested by the SGA unit test suite, but the coverage report for the accel tests only reports coverage for the accel repo code.  
3. Do you see a way to combine the integration tests (running against a live CBS) with this test coverage tool?  If not, do we have a path forward to getting accurate coverage numbers for things like DCP and xattrs?

**Review by adamcfraser — COMMENTED** [review]
Changes here look good, but have a few questions on the tool as a whole that I added to the PR.

**Comment by tleyden** [comment]
I don't think averaging the coverage numbers of the packages would actually make sense, since it wouldn't take into account the number of lines of code in the package.. and the average would need to be weighted according to that.

Eg, if you have two packages:

* PackageA: 1 million lines of code with coverage 100%
* PackageB: 2 lines of code with coverage 100%

and then 2 more lines of code were added to PackageB without any test coverage, the overall average would drop from 100% -> 50%, rather than the expected 100% -> 99.99%

**Comment by tleyden** [comment]
@adamcfraser I realized there is a complication with running the unit integration tests in conjunction with the code coverage, due to the fact that we are working around https://github.com/couchbase/sync_gateway/issues/2612 by looping over the individual tests with:

```

  declare -a arr=(
    "TestChannelCacheSize"
    "TestChangesAfterChannelAdded"
    "TestDocDeletionFromChannelCoalescedRemoved"
    "TestDocDeletionFromChannelCoalesced"
   ....
  )

  for i in "${arr[@]}"
  do
      go test -v -run ^"$i"$ $SG_PACKAGES
  done
```

This would require a lot of intermediate coverage files and merging.   I think it might be better to try to tackle the root problem in  https://github.com/couchbase/sync_gateway/issues/2612 rather than add complexity on top of complexity.

My initial plan was just to ignore the https://github.com/couchbase/sync_gateway/issues/2612 issues (which I think might be failing sporadically) and run the full test suite via:

```
  gocoverutil -coverprofile=cover_sg.out test -v -covermode=count github.com/couchbase/sync_gateway/...
```

With the environment variables set to run the unit tests in integration mode.

**Comment by tleyden** [comment]
Since the latest round of changes to `test.sh` require so many changes to the Jenkins job, I created a brand new job here:

http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/2/

once this PR is closed, I'll consolidate the two jobs into one

**Comment by tleyden** [comment]
screen shot 2017-09-08 at 1 46 37 pm

* [11](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/11/parameters/) -- code coverage + integration tests, not passing -- I'm assuming this is due to  https://github.com/couchbase/sync_gateway/pull/2880#issuecomment-327932768

* [12](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/12/parameters/) + [13](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/13/parameters/)  -- integration tests without code coverage, passes (no regression w/ this change)

* [14](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/14/parameters/) -- Walrus tests + code coverage, passes and adds coverage report.

**Comment by tleyden** [comment]
Some issues with this PR:

- I don't know how comfortable I am with the changes in `test.sh`.  I had to some hacky workarounds to have it propagate the some of the args to the underlying go tooling.  It feels overcomplicated and probably merits more effort to clean this up.

**Comment by tleyden** [comment]
After discussion w/ @adamcfraser, the plan is to park the "unified test.sh" change until we can vet this change further.  It's on the [feature/issue_2836_code_coverage_unified_test_sh](https://github.com/couchbase/sync_gateway/tree/feature/issue_2836_code_coverage_unified_test_sh) branch.  (I'll open a separate tracking ticket)

The plan for this PR is to revert back to the approach where it uses a separate script, and does not attempt to add code coverage for the integration tests.

**Comment by tleyden** [comment]
Reverted this PR to the original change.

Example jenkins unit integration test run:

http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/270/

Ready to merge.

**Pull request merged**
