### PR TITLE
CBG-703: Evaluate usages of time.After and consider time.Ticker

### PR DESCRIPTION
**Pull request by sarathkumarsivan**

### CODE REVIEW

**Review by bbrks — DISMISSED** [review]
LGTM, failing test in CI is an existing blip test race, will leave for sync up for final go-ahead/merge.

**Comment by bbrks** [comment]
@sarathkumarsivan Can you rebase this onto master now the repo fix ( #4489 ) is in so we can get a clean build?

**Comment by sarathkumarsivan** [comment]
Sure @bbrks. Just rebased this onto master and force-pushed.

**Review by bbrks — APPROVED** [review]
LGTM

**Pull request merged**
