### PR TITLE
Add support for "*" log key, which enables all key-based logging

### LINKED ISSUE #610: "Verbose" flag for log topic config
It would be cool if there was a way to turn on all logging without listing every log tag. Forward compatible with new log tags, etc...

This way test automation can use this flag and developers will always have useful logs when tests fail.

### PR DESCRIPTION
**Pull request by adamcfraser**
Fixes #610

### CODE REVIEW

**Comment by adamcfraser** [comment]
One implementation note I accidentally left off the commit - I'm doing some additional work to set the logStar flag, instead of just checking for logKeys[*] in LogTo - this is to avoid the overhead of an additional map lookup every time we call LogTo for a disabled key.

**Comment by jchris** [comment]
looks good to me -- do we merge with the big green button?

**Comment by tleyden** [comment]
@JeffThomasWriter I just tagged this as needing docs.

**Comment by tleyden** [comment]
@JeffThomasWriter I should say "potentially needing", because I didn't make sure it's not already in the docs.

**Comment by adamcfraser** [comment]
The original ticket notes the doc requirement - I'll reassign that to @JeffThomasWriter

**Pull request merged**
