### PR TITLE
support getting design docs bulk and getAllDocs apis

### PR DESCRIPTION
**Pull request by fredericgermain**
rework of https://github.com/couchbase/sync_gateway/pull/2959, I'm not sure what happened, I was working from version 1.4.1.2...

this is get keep compat with couchdb, I'm trying to make https://github.com/colinskow/superlogin/issues/170 works

### CODE REVIEW

**Comment by fredericgermain** [comment]
Automatic build failed, at fetch source step, I'm not sure why...

error: Cannot fetch sync_gateway (GitError: sync_gateway update-ref: fatal: 80766892b0991dfe8c87c7e406f5aa5d48f2bbec^0: not a valid SHA1

In the meantime, I made a small change in my change request as there was small change of API between 1.4.1.2 and master...

**Comment by tleyden** [comment]
@fredericgermain not sure I fully understand the issue this is trying to fix.  Can you post an "actual" vs "expected" for the REST API?

**Comment by fredericgermain** [comment]
For GET,

Before:
```
GET /karaouser/_all_docs?include_docs=true&keys=%5B%22_design%2Fauth%22%5D HTTP/1.1
Accept: application/json
Content-Type: application/json
host: localhost:4985
Connection: close

HTTP/1.1 200 OK
Content-Type: application/json
Server: Couchbase Sync Gateway/1.4.1
Date: Fri, 20 Oct 2017 19:17:00 GMT
Content-Length: 101
Connection: close

{"rows":[
{"key":"_design/auth","error":"bad_request","status":400}
],
"total_rows":1,"update_seq":1}
```
After:
```
GET /karaouser/_all_docs?include_docs=true&keys=%5B%22_design%2Fauth%22%5D HTTP/1.1
Accept: application/json
Content-Type: application/json
host: localhost:4985
Connection: close

HTTP/1.1 200 OK
Content-Type: application/json
Server: Couchbase Sync Gateway/1.5 branch/superlogin commit/b5f5b0b
Date: Fri, 20 Oct 2017 19:10:22 GMT
Connection: close
Transfer-Encoding: chunked

800
{"rows":[
{"views":{"email":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function (doc) {\n        if(doc.email) {\n          emit(doc.email, null);\n        } else if(doc.unverifiedEmail.email) {\n          emit(doc.unverifiedEmail.email, null);\n        }\n      }) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"emailUsername":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function (doc) {\n        emit(doc._id, null);\n        if(doc.email) {\n          emit(doc.email, null);\n        } else if(doc.unverifiedEmail.email) {\n          emit(doc.unverifiedEmail.email, null);\n        }\n      }) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"expiredKeys":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function (doc) {\n        if(doc.session) {\n          for(var key in doc.session) {\n            if(doc.session.hasOwnProperty(key) \u0026\u0026 doc.session[key].expires) {\n              emit(doc.session[key].expires, {key: key, user: doc._id});\n            }\n          }\n        }\n      }) (do
e05
c, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"facebook":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function(doc) {\n  if(doc.facebook \u0026\u0026 doc.facebook.profile) {\n    emit(doc.facebook.profile.id, null);\n  }\n}) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"google":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function(doc) {\n  if(doc.google \u0026\u0026 doc.google.profile) {\n    emit(doc.google.profile.id, null);\n  }\n}) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"passwordReset":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function (doc) {\n        if(doc.forgotPassword \u0026\u0026 doc.forgotPassword.token) {\n          emit(doc.forgotPassword.token, null);\n        }\n      }) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"session":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function (doc) {\n        if(doc.session) {\n          for(var key in doc.session) {\n            if(doc.session.hasOwnProperty(key)) {\n              emit(key, doc._id);\n            }\n          }\n        }\n      }) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"username":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function (doc) {\n        emit(doc._id, null);\n      }) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"},"verifyEmail":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function (doc) {\n        if(doc.unverifiedEmail \u0026\u0026 doc.unverifiedEmail.token) {\n          emit(doc.unverifiedEmail.token, null);\n        }\n      }) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"}}}

21
],
"total_rows":0,"update_seq":1}
0

```

**Comment by fredericgermain** [comment]
For POST,

before
```
POST /karaouser/_bulk_docs HTTP/1.1
Accept: application/json
Content-Type: application/json
host: localhost:4985
content-length: 1755
Connection: close

{"docs":[{"_id":"_design/auth","views":{"email":{"map":"function (doc) {\n        if(doc.email) {\n          emit(doc.email, null);\n        } else if(doc.unverifiedEmail.email) {\n          emit(doc.unverifiedEmail.email, null);\n        }\n      }"},"username":{"map":"function (doc) {\n        emit(doc._id, null);\n      }"},"verifyEmail":{"map":"function (doc) {\n        if(doc.unverifiedEmail && doc.unverifiedEmail.token) {\n          emit(doc.unverifiedEmail.token, null);\n        }\n      }"},"emailUsername":{"map":"function (doc) {\n        emit(doc._id, null);\n        if(doc.email) {\n          emit(doc.email, null);\n        } else if(doc.unverifiedEmail.email) {\n          emit(doc.unverifiedEmail.email, null);\n        }\n      }"},"passwordReset":{"map":"function (doc) {\n        if(doc.forgotPassword && doc.forgotPassword.token) {\n          emit(doc.forgotPassword.token, null);\n        }\n      }"},"session":{"map":"function (doc) {\n        if(doc.session) {\n          for(var key in doc.session) {\n            if(doc.session.hasOwnProperty(key)) {\n              emit(key, doc._id);\n            }\n          }\n        }\n      }"},"expiredKeys":{"map":"function (doc) {\n        if(doc.session) {\n          for(var key in doc.session) {\n            if(doc.session.hasOwnProperty(key) && doc.session[key].expires) {\n              emit(doc.session[key].expires, {key: key, user: doc._id});\n            }\n          }\n        }\n      }"},"facebook":{"map":"function(doc) {\n  if(doc.facebook && doc.facebook.profile) {\n    emit(doc.facebook.profile.id, null);\n  }\n}"},"google":{"map":"function(doc) {\n  if(doc.google && doc.google.profile) {\n    emit(doc.google.profile.id, null);\n  }\n}"}}}],"new_edits":true}HTTP/1.1 201 Created
Content-Length: 84
Content-Type: application/json
Server: Couchbase Sync Gateway/1.4.1
Date: Fri, 20 Oct 2017 19:17:00 GMT
Connection: close

[{"error":"bad_request","id":"_design/auth","reason":"Invalid doc ID","status":400}]
```

After
```
POST /karaouser/_bulk_docs HTTP/1.1
Accept: application/json
Content-Type: application/json
host: localhost:4985
content-length: 1755
Connection: close

{"docs":[{"_id":"_design/auth","views":{"email":{"map":"function (doc) {\n        if(doc.email) {\n          emit(doc.email, null);\n        } else if(doc.unverifiedEmail.email) {\n          emit(doc.unverifiedEmail.email, null);\n        }\n      }"},"username":{"map":"function (doc) {\n        emit(doc._id, null);\n      }"},"verifyEmail":{"map":"function (doc) {\n        if(doc.unverifiedEmail && doc.unverifiedEmail.token) {\n          emit(doc.unverifiedEmail.token, null);\n        }\n      }"},"emailUsername":{"map":"function (doc) {\n        emit(doc._id, null);\n        if(doc.email) {\n          emit(doc.email, null);\n        } else if(doc.unverifiedEmail.email) {\n          emit(doc.unverifiedEmail.email, null);\n        }\n      }"},"passwordReset":{"map":"function (doc) {\n        if(doc.forgotPassword && doc.forgotPassword.token) {\n          emit(doc.forgotPassword.token, null);\n        }\n      }"},"session":{"map":"function (doc) {\n        if(doc.session) {\n          for(var key in doc.session) {\n            if(doc.session.hasOwnProperty(key)) {\n              emit(key, doc._id);\n            }\n          }\n        }\n      }"},"expiredKeys":{"map":"function (doc) {\n        if(doc.session) {\n          for(var key in doc.session) {\n            if(doc.session.hasOwnProperty(key) && doc.session[key].expires) {\n              emit(doc.session[key].expires, {key: key, user: doc._id});\n            }\n          }\n        }\n      }"},"facebook":{"map":"function(doc) {\n  if(doc.facebook && doc.facebook.profile) {\n    emit(doc.facebook.profile.id, null);\n  }\n}"},"google":{"map":"function(doc) {\n  if(doc.google && doc.google.profile) {\n    emit(doc.google.profile.id, null);\n  }\n}"}}}],"new_edits":true}HTTP/1.1 201 Created
Content-Length: 33
Content-Type: application/json
Server: Couchbase Sync Gateway/1.5 branch/superlogin commit/b5f5b0b
Date: Fri, 20 Oct 2017 19:21:48 GMT
Connection: close

[{"id":"_design/auth","rev":"0"}]
```

**Comment by tleyden** [comment]
@fredericgermain this was discussed at the last team meeting, and there are some risks associated w/ accepting this PR right now.

I believe the risks had to do with breaking existing behavior.  @adamcfraser do you happen to remember the details on this?  I think one risk was accidentally breaking the `total_rows` count with this change.

**Comment by adamcfraser** [comment]
We're not planning to go ahead with this change, based on the concerns outlined above.

**Pull request closed without merging**
