### PR TITLE
Inclusive_end should be true if not specified

### LINKED ISSUE #3032: TestSessionAPI disabled integration test
TestSessionAPI fails with xattr=true and xattr=false:

```
$ SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://localhost:8091 SG_TEST_USE_XATTRS=false ./test.sh -run ^TestSessionAPI$
Testing code with 'go test' ...
Integration mode: forcing tests to run in serial across packages via -p 1 flag
Running Sync Gateway unit tests
=== RUN   TestSessionAPI
2017-11-06T16:46:38.867-08:00 NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-11-06T16:46:47.142-08:00 WARNING: TestBucketManager.EmptyBucket(): still 1 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:327
2017-11-06T16:46:47.664-08:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://localhost:8091> as user "test_data_bucket"
2017-11-06T16:46:47.669-08:00 NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-11-06T16:46:47.669-08:00 NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-11-06T16:46:47.669-08:00 Opening db /db as bucket "test_data_bucket", pool "default", server <http://localhost:8091>
2017-11-06T16:46:47.669-08:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://localhost:8091> as user "test_data_bucket"
2017-11-06 16:46:48.145247 I | bucketDataSource.Start() called
2017-11-06T16:46:48.146-08:00 Using default sync function 'channel(doc.channels)' for database "db"
goroutine 18 [running]:
runtime/debug.Stack(0xc420165ce0, 0xc420165ce0, 0x12d4e54)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/couchbase/sync_gateway/rest.assertStatus(0xc4201f20f0, 0xc4201be560, 0x194)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:392 +0x5f
github.com/couchbase/sync_gateway/rest.TestSessionAPI(0xc4201f20f0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api_test.go:724 +0xbab
testing.tRunner(0xc4201f20f0, 0x18e8fa0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
--- FAIL: TestSessionAPI (11.82s)
	utilities_testing.go:393: Response status 200 (expected 404) for GET <http://localhost/db/_session/d4d39b6d6c6520d839ea8fb9c0b82bc4dd4524a5> : {"authentication_handlers":["default","cookie"],"ok":true,"userCtx":{"channels":{"!":1},"name":"user2"}}
2017-11-06 16:46:50.686619 I | bucketDataSource.Close() called
FAIL
exit status 1
FAIL	github.com/couchbase/sync_gateway/rest	11.839s
```

Original issue: https://github.com/couchbase/sync_gateway/issues/2977

### PR DESCRIPTION
**Pull request by adamcfraser**
Default value of inclusive_end in Couchbase Server, if not specified, is true.

Fixes #3032, #3078

### CODE REVIEW

**Comment by adamcfraser** [comment]
Tested directly against the bucket to verify server behaviour:
```
http://127.0.0.1:8092/test_data_bucket/_design/sync_housekeeping/_view/sessions?limit=6&stale=false&connection_timeout=60000&skip=0&full_set=&startkey=%22user2%22&endkey=%22user2%22
```
No inclusive_end specified, returns 5 rows

```
http://127.0.0.1:8092/test_data_bucket/_design/sync_housekeeping/_view/sessions?limit=6&stale=false&connection_timeout=60000&skip=0&full_set=&startkey=%22user2%22&endkey=%22user2%22&inclusive_end=false
```
Inclusive_end=false, returns 0 rows

**Comment by adamcfraser** [comment]
Integration test:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/137/

**Comment by adamcfraser** [comment]
This change is breaking TestChangesActiveOnlyWithLimitLowRevCache, but it looks to me like a bug in the changes view processing - reviewing.

**Comment by adamcfraser** [comment]
Need to review whether there's a 1.5.0 channel cache bug because the channels view was using inclusive_end=false, and so not getting the overlapping sequence expected here:
https://github.com/couchbase/sync_gateway/blob/master/db/channel_cache.go#L344

This would result in the channel cache not getting prepended after view query.

**Comment by adamcfraser** [comment]
Integration test re-run:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/138/

**Comment by adamcfraser** [comment]
Added unit test for #3078.  Integration test re-run:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/139/

**Comment by tleyden** [comment]
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/139/console failed with:

```
"last_seq":"9"}

	api_test.go:1805
	assert.Equals(t, len(changes.Results), len(expectedIDs))	

	expected: 9
	     got: 8
2017-11-16T14:16:10.872-08:00 Changes+: changeListener.Stop() called
--- FAIL: TestChannelAccessChanges (6.52s)
	assert.go:31: 
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

```

**Comment by tleyden** [comment]
`TestChannelAccessChanges` is a sporadic failure logged here: https://github.com/couchbase/sync_gateway/issues/3069

**Comment by tleyden** [comment]
`--- PASS: TestChangesViewBackfill (8.00s)` passing in integration test mode

**Pull request merged**
