### PR TITLE
CBG-488 Enable cbgt gocb-based DCP client

### PR DESCRIPTION
**Pull request by adamcfraser**
Adds Dest implementation to support cbgt's gocb-based client.  Currently instantiates client directly to avoid manager overhead for full DCP feed (caching feed).  Dest implementation will be reused by sharded feed implementation (import feed).

Removed bucket notify function, as it was a legacy of tap feed, and wasn't being called by DCP feed.

Still requires manifest update to pick up pending fix in cbgt, updates to sg-bucket and addition of cbgt dependencies.

- [x] http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/1292/
- [ ] http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/1293/

### CODE REVIEW

**Comment by adamcfraser** [comment]
ee build failure is TestContinuousChangesBackfill (https://issues.couchbase.com/browse/CBG-520).  Haven't been able to repro locally (even under -race).

**Review by bbrks — CHANGES_REQUESTED** [review]
This mostly looks good - aside from the couple of TODOs (like `makeVbucketMetadataForSequence`) and the comments left below.

**Comment by adamcfraser** [comment]
Integration tests are hitting a panic in cbgt code on timeout when opening a stream:
```
2019/09/27 07:20:25 feed_gocb_dcp: NewGocbDCPFeed, name: SG-v-2.7-commit--uuid-f2ba578e-e131-11e9-be33-2a203e062299, indexName: SG-v-2.7-commit--uuid-f2ba578e-e131-11e9-be33-2a203e062299
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa657ab]

goroutine 1281 [running]:
github.com/couchbase/cbgt.(*GocbDCPFeed).initiateStreamEx.func2(0xc0007b0ee0, 0x0, 0x0, 0xc000308000, 0xc0004703a1)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/cbgt/feed_dcp_gocb.go:388 +0xeb
created by github.com/couchbase/cbgt.(*GocbDCPFeed).initiateStreamEx
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/cbgt/feed_dcp_gocb.go:380 +0x194
FAIL	github.com/couchbase/sync_gateway/rest	76.886s
```

http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/1288/

It's possible this is due to previous streams not being properly closed on test teardown, but the code also shouldn't be panicking.

**Comment by adamcfraser** [comment]
The gocb teardown issue appears to be an issue in cbgt - filed https://issues.couchbase.com/browse/MB-36207.  Until that's fixed, have switched to have Sync Gateway's cbgt integration use cbdatasource.  There's a gap in x.509 coverage for cbgt+cbdatasource - filed CBG-526 to track this in the event we want to retain the option to use cbgt+cbdatasource in GA.

Integration tests look better with cbgt+cbdatasource - non-xattr is clean, and xattr failed on an unrelated test issue (filed CBG-525 to fix).

**Comment by adamcfraser** [comment]
Reran integration tests with the cbgt fix for the waitgroup issue.  Generally much more successful, but three items need attention:
- cbgt logging is very noisy on client side feed close (i.e. test tear down).  Resulted in 54MB of logs for this test.  This could be addressed on the cbgt side, either by changing logging or supporting more graceful client shutdown (terminator channel for goroutines, etc).  
- We need to standardize cbgt logging into SG's format, which may be possible via global clog handling.  
- TestViewQueryTombstoneRetrieval is actually failing - need to review whether this can be reproduced locally against CBS

Integration test:
http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/1300/

**Comment by bbrks** [comment]
http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/1304/

**Review by bbrks — APPROVED** [review]

**Pull request merged**
