### PR TITLE
#1977: Improve CLI usage information

### LINKED ISSUE #1977: Improve sg_collect_info command line docs
I want to test sg collect info so that it actually uploads, and looking at the CLI help it shows:

```
  --upload-host=UPLOAD_HOST
                        gather diagnotics and upload it for couchbase support.
                        Gives upload host
  --customer=UPLOAD_CUSTOMER
                        specifies customer name for upload
  --ticket=UPLOAD_TICKET
                        specifies support ticket number for upload
```

This is confusing!  Do I need to specify all of these or just one of these?  What does "Gives upload host" mean?

@mattcarabine can you update this in the script itself or in the ticket and I will update the script?  I think providing examples and mentioning constraints would be useful.  For example:

```
  --ticket=UPLOAD_TICKET
                        Specifies support ticket number for upload, eg, CBSE-12334.  This ticket must exist or else it will fail.  Contact support@couchbase.com if you don't have a ticket and need one created for you.
```

### PR DESCRIPTION
**Pull request by mattcarabine**
This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1985)

Resolves #1977

### CODE REVIEW

**Comment by tleyden** [comment]
@mattcarabine thanks, looks like a big improvement!  Is `--upload-host` required or optional?

**Comment by mattcarabine** [comment]
So it's kind of difficult to encapsulate nicely in the CLI usage docs, perhaps this is more something that can be discussed in the actual documentation.... It won't upload the logs unless you specify an upload-host, but if you do you also need the customer and the ticket number.

**Comment by tleyden** [comment]
Why does the user even need to specify `--upload-host`?  

Why not have it so that if a customer and a ticket number is supplied, it will upload to s3.amazonaws.com/cb-customers by default?

If for some reason (seems uncommon), a different upload host should be used, they can override it by adding the `--upload-host` flag?

**upload_ticket help**: "specifies the support ticket number for the upload.  e.g 1234 (must be numeric), contact Couchbase Support to open a new ticket if you don't already have one.  you must also provide the upload_customer flag if this is used"

**upload_customer help**: "specifies the customer name for the upload.  this is an arbitrary string, but please use something that makes it easy to identify you or your company, eg, Acme, Inc"

**upload_host help**: "if you specified upload_ticket and upload_customer, and need to override the default host (s3.amazonaws.com/cb-customers), then specify the alternate upload host here"

**Comment by mattcarabine** [comment]
So the problem is, what if you want to collect logs _without_ uploading them, do we then have to add a further flag that say '--no-upload'?

To me it doesn't seem to make much difference, but one of the two options is already in place.

**Comment by tleyden** [comment]
> So the problem is, what if you want to collect logs without uploading them, do we then have to add a further flag that say '--no-upload'?

I think you would just not specify upload_customer or upload_ticket in that case.

```
if upload_customer and upload_ticket:
   upload to s3.amazonaws.com/cb-customers or whatever user specified in upload_host
else if upload_customer but not upload_ticket, or vice-versa:
   print an error saying that both must be specified
else if neither upload_customer or upload_ticket:
   collect logs but do not upload to s3 
```

**Comment by tleyden** [comment]
If that's a bigger change than we want for this PR .. how about changing the upload_host help to: "when specifying upload_customer and upload_ticket to upload the logs to a support ticket, you must also specify an upload_host.  Use s3.amazonaws.com/cb-customers unless you've been instructed otherwise by Couchbase Support."

**Comment by tleyden** [comment]
Gonna merge this since it improves things from previous.  But I think we can improve things even more per previous discussion.

**Pull request merged**
