### PR TITLE
Feature/issue 2639 better err msg views

### LINKED ISSUE #2639: Better error reporting needed when views are not ready
Filing this issue on behalf of @suravarjjala 

### Sync Gateway version
1.5.0

### Operating system
Windows

### Steps to reproduce
- Install and configure a couchbase server
- Add a lot of docs to the bucket, in this case there were 80 million docs
- Try to add a doc to SG

### Actual behavior
» curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{}' 'http://<SG_IP>:4984/db/Test?new_edits=true'
{"error":"Internal Server Error","reason":"Internal error: Get http://localhost:8092/default-ycsb/_design/sync_gateway/_view/access?key=%22%22\u0026stale=false: net/http: request canceled"}%

### Expected behavior
An appropriate message saying that the views are not yet ready should be logged

### Requirements 

- [ ] Return 503 error instead of 500

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #2639

### CODE REVIEW

**Comment by adamcfraser** [comment]
Will merge to master once 1.5 beta refresh is wrapped.  Can be backported to release/1.4.1.1 branch in the meantime.

**Comment by tleyden** [comment]
@adamcfraser this can't be backported to release/1.4.1.1, because it doesn't do view queries via gocb.  Here's the [gocb bucket code](https://github.com/couchbase/sync_gateway/blob/release/1.4.1.1/base/bucket_gocb.go#L1052-L1060):

```
func (bucket CouchbaseBucketGoCB) View(ddoc, name string, params map[string]interface{}) (sgbucket.ViewResult, error) {
	LogPanic("Unimplemented method: View()")
	return sgbucket.ViewResult{}, nil
}

func (bucket CouchbaseBucketGoCB) ViewCustom(ddoc, name string, params map[string]interface{}, vres interface{}) error {
	LogPanic("Unimplemented method: ViewCustom()")
	return nil
}
```

Or is the idea to come up w/ the same solution for go-couchbase based view queries?

**Comment by adamcfraser** [comment]
@tleyden Ah right - the 1.4 version will have to be based on the go-couchbase timeout message formatting.

**Comment by tleyden** [comment]
@adamcfraser there's another snag with this.  From what I can tell, go-couchbase doesn't have any notion of timeouts when it does a view query.  It blocks indefinitely.

**Comment by tleyden** [comment]
The import related build errors are fixed now

**Comment by tleyden** [comment]
Reworked to use the typed error ErrViewTimeoutError.  Ready for re-review assuming build + tests pass

**Comment by tleyden** [comment]
Since this PR is still on a feature branch, I stacked the fix for #2699 onto this PR: 
 See commit https://github.com/couchbase/sync_gateway/pull/2746/commits/a12781fa3e3f62920596025e577fbec9f745d12a

**Comment by tleyden** [comment]
@adamcfraser this is rebased and ready to merge once the CI build is done

**Comment by tleyden** [comment]
@adamcfraser this is rebased again and ready to merge once the CI build is done

**Pull request merged**
