### PR TITLE
Added CORS support

### PR DESCRIPTION
**Pull request by ssured**
To enable CORS support, add this to your config.json:

```
  "CORS": {
    "Origin": ["https://home.muse.net.nz:8000", "http://localhost", "http://www.number10.gov.uk:80"],
    "Headers": ["DNT","X-Mx-ReqToken","Keep-Alive","User-Agent","X-Requested-With","If-Modified-Since","Cache-Control","Content-Type"],
    "MaxAge": 1728000
  }
```

`Origin`, `Headers` and `MaxAge` all need to be defined. Use `"Origin":["*"]` to enable access from anywhere.

### CODE REVIEW

**Comment by zgramana** [comment]
In reviewing this with @adamcfraser, I think restricting the URI's to which CORS policies can be applied to just the replication protocol endpoints would be appropriate from a security perspective. This would exclude the admin, user, and session API's. These could be revisited later.

**Comment by janober** [comment]
Any updates on this? Did also just run into issue #115 and having that fixed would be really great!

**Comment by zgramana** [comment]
For future reference: https://code.google.com/p/xsrftoken/

**Comment by zgramana** [comment]
For those who need help now, and don't want to use a custom SG build: http://enable-cors.org/server_nginx.html

**Comment by zgramana** [comment]
Another thing we can consider is warning when CORS is enabled and the admin interface is not just listening on the local loopback.

**Comment by jchris** [comment]
rebased at #695

**Comment by jchris** [comment]
moving discussion to #115

**Pull request closed without merging**
