### PR TITLE
Catch missed teardownFn calls in SetUpTestLogging

### PR DESCRIPTION
**Pull request by bbrks**
This should make it easier to spot when tests have accidentally skipped resetting the logging in between tests.

- Will make `SetUpTestLogging` panic if a previous test has not called the teardownFn.
- Fixed tests which were not correctly setting up or tearing down logging settings.

## Companion PR:
- [x] https://github.com/couchbaselabs/sync-gateway-accel/pull/213
- [x] Update manifest in SG for the above changes

### CODE REVIEW

**Comment by bbrks** [comment]
Turns out this change uncovered a bunch of tests that weren't resetting the logging! I'll go ahead and fix those as part of this PR.

**Comment by bbrks** [comment]
Need a companion PR in accel before this can be merged.

**Comment by tleyden** [comment]
I see the link to the companion PR, but it's still saying "continuous-integration/jenkins/pr-head — This commit cannot be built".  Any idea?

**Comment by bbrks** [comment]
@tleyden The manifest for accel needs to be bumped in this PR before those tests pass.

**Comment by tleyden** [comment]
You should be able to bump it on this SG PR branch, even though it will should get "re-bumped" to point to SG Accel master after the accel PR is merged.   That way we can verify there are no test regressions from the perspective of the SG test suite before even merging the accel PR.

**Comment by bbrks** [comment]
@tleyden good point, thanks. I forgot I could supply a non-master branch checksum. I'll update now.

**Comment by tleyden** [comment]
Can you update the manifest to point to the master branch of SG Accel?

**Comment by bbrks** [comment]
@tleyden done

**Review by adamcfraser — APPROVED** [review]

**Pull request merged**
