### PR TITLE
Allow users to perform view queries, on views created through the SG admin REST API.

### LINKED ISSUE #449: Add view queries to client API
Continuing from #379, opening the view query REST API to clients. The major tasks with this are security related — filtering the query results to rows that were emitted only by docs visible to the user.

### PR DESCRIPTION
**Pull request by snej**
Result sets are filtered by user access privileges: no rows are returned that were generated by
documents the user can't read.
Fixes #449

### CODE REVIEW

**Comment by tleyden** [comment]
As part of review:
- [x] Write a document that explains how to use this feature
- [x] Test this on a real setup with TodoLite dataset

**Comment by tleyden** [comment]
While testing this, I ran into [this panic](https://gist.github.com/tleyden/23090bd3d8711aad1950)

Digging into it.

**Comment by snej** [comment]
Panic was because the query row's value was a string not an `[]interface{}`. Probably because the design doc was created in the Couchbase admin UI (or direct REST call to the db view server) not through the SG REST API — I don't think I spelled that requirement out well enough in the commit log or comments.

**Comment by snej** [comment]
The JavaScript code added in this patch substitutes a new `emit` function that wraps the actual emitted value in an array that also contains the document's list of channels. That allows the `filterViewResult` function to efficiently check whether each row should be visible to the caller.

If anyone can think of an efficient way to filter that doesn't require altering the map function, that would be great. I can already see that this may become a frequent developer mistake, since it isn't at all obvious from the outside that you can't create the design doc outside of SG.

**Comment by tleyden** [comment]
> Probably because the design doc was created in the Couchbase admin UI (or direct REST call to the db view server) not through the SG REST API 

Ah, yes, I created it my view via the Couchbase admin UI.  I'm in the process of writing a "guide" on how to use views from Sync Gateway, so I'll update it to mention that design docs must be created via the SG REST API.

> The JavaScript code added in this patch substitutes a new emit function that wraps the actual emitted value in an array that also contains the document's list of channels

I'm not seeing the a new commit mentioned in this comment.  Also what problem does this solve?  (speeding things up or extending existing functionality?)

**Comment by tleyden** [comment]
When testing on port 4984, the "total_rows" seems to be off:

```
{
    "total_rows":5,
    "rows":[
        {
            "id":"57b82878-a7dc-478a-80c1-e2700f8f5a11",
            "key":"Food",
            "value":"profile:778915335487383"
        },
        {
            "id":"9fb28b8c-ed2a-49e3-a466-ca98dc20c42f",
            "key":"Movies",
            "value":"profile:778915335487383"
        }
    ]
}
```

**Comment by tleyden** [comment]
> When testing on port 4984, the "total_rows" seems to be off:

As it turns out, total_rows is total rows in the view, _before_ filtering: http://docs.couchdb.org/en/latest/json-structure.html

**Comment by tleyden** [comment]
Add new guide to docs: https://github.com/couchbaselabs/couchbase-mobile-portal/commit/930b564d9f9d9b96336913a82b1a53eed0d11add

**Pull request merged**
