### PR TITLE
Feature/issue 2653

### LINKED ISSUE #2653: Build Active Replicator For Blip And Initial Unit Test
Need to get automated unit tests for sync gateway blip replication

### PR DESCRIPTION
**Pull request by ajres**
fixes #2653 

Commit of initial refactor of blip_sync to external repo

### CODE REVIEW

**Comment by tleyden** [comment]
@ajres so it looks like this PR is basically a refactor to get the code into the https://github.com/couchbaselabs/go-blip-sync repo.  Is the plan to do a follow-up PR to add additional unit tests for go-blip-sync?  

I'm a little confused since this PR says it closes https://github.com/couchbase/sync_gateway/issues/2653, but the description on 2653 is "Need Unit Tests For Blip", and I'm not seeing much in the way of additional unit tests in this PR.

**Comment by tleyden** [comment]
This PR needs to be rebased on to master, which is further complicated by the fact that  @adamcfraser's commits to `rest/blip_sync.go`: 

https://github.com/couchbase/sync_gateway/commit/1dc0138e09ebdf6a5d7f5bd6867d39ff07384b1f#diff-38c665ab7cbb8a588d5fa588e88bbc72

will need to get into the codebase somehow.  Looks like these should get pushed to https://github.com/couchbaselabs/go-blip-sync, so I'll open a separate PR for that.

**Comment by adamcfraser** [comment]
I don't think the refactoring proposed in this PR really makes sense.  The migrated code has a heavy dependency on a Sync Gateway database instance (BlipSyncHandler.db), so doesn't really provide much value as a standalone library (in go-blip-sync).

**Review by adamcfraser — CHANGES_REQUESTED** [review]
I don't see the benefit of moving the blip-sync code to its own library if it still retains significant dependencies on the SG codebase.

**Comment by tleyden** [comment]
I didn't realize https://github.com/couchbaselabs/go-blip-sync had a dependency back to the Sync Gateway codebase.  Yeah that feels like a circular dependency on a conceptual level.

**Comment by tleyden** [comment]
Closing as a duplicate of https://github.com/couchbase/sync_gateway/pull/3191

**Pull request closed without merging**
