### PR TITLE
Add 1.4.0 branch manifest

### PR DESCRIPTION
**Pull request by ceejatec**

### CODE REVIEW

**Comment by tleyden** [comment]
LGTM -- @adamcfraser I assigned to you to merge

**Comment by adamcfraser** [comment]
I think I'd been assuming that we're storing the release build manifests here:
https://github.com/couchbase/build-team-manifests/tree/master/sync_gateway

Now that I look a little closer, the versions in build-team-manifests are just whatever the last build was for that release number, not the actual GA build.  Is that the problem this PR is correcting?

**Comment by ceejatec** [comment]
This isn't a "build manifest", it's a new input manifest for a product branch. This could contain git branches for further 1.4.x releases. For now it's just locked to SHAs of the build we decided to release as 1.4.0.

**Comment by adamcfraser** [comment]
OK - thanks for the context.

**Pull request merged**
