### PR TITLE
New unit test for Feature/issue 1527

### PR DESCRIPTION
**Pull request by ajres**
Issue #1527 was identified during a test fest session.

If there are any active REST calls blocked reading from an (undetected) closed client connection, the _offline request will hang until the blocked connection is closed on the SG server which may take up to 2 hours.

This prevents the DB being taken offline and requires an SG restart to release the blocked calls.

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1534)

### CODE REVIEW

**Comment by tleyden** [comment]
@ajres can you squash these into a single commit?  Also, [this commit](https://github.com/couchbase/sync_gateway/commit/35d89ead12c4163b9e28289e1a02e3ed75ccda9e) shouldn't be included, just the commits which add the new unit tests.

**Comment by tleyden** [comment]
@adamcfraser can be merged after 1.2 is tagged..

**Comment by adamcfraser** [comment]
@ajres Based on the build output, your goroutines aren't ending within the scope of the test, and are bleeding API calls into subsequent tests.

**Comment by ajres** [comment]
This wasn't intended to be merged, it was pushed to share with @tleyden, I was running this test in isolation to try and repo #1527.

Since this does not repro #1527, I don't think it has value a unit test.

**Comment by adamcfraser** [comment]
@ajres I like the idea of having a unit test that mimics CBL replication - maybe we can revisit and make it a bit more robust in 1.3?

**Comment by ajres** [comment]
Agree that would be good, might need some updates to the test harness, this unit test generates multiple data race failures (in test harness) when run with -race flag.

**Comment by tleyden** [comment]
Yeah we should definitely clean this up and get this in:
- Serves as a good example 
- Could potentially find future regressions

**Comment by adamcfraser** [comment]
Closing this - replication scenarios are well covered by functional tests, not critical in the unit test framework.

**Pull request closed without merging**
