### PR TITLE
Expiry support for SG documents

### LINKED ISSUE #1823: TTL support for Sync Gateway

### PR DESCRIPTION
**Pull request by adamcfraser**
When writing a document to Sync Gateway (via PUT doc or bulk_docs), users can set the '_exp' property in the body of the document.  When Sync Gateway writes the document, it will:
- Set a Couchbase Server expiry on the document, based on the exp value (see below for format)
- Strip the _exp property from the document body (to avoid compatibility issues around the leading underscore when that document is replicated elsewhere)
- Set an expiry property - `exp` - in the document's sync metadata, to provide some visibility on the expiry value

When Sync Gateway reads a document (via document GET, bulk_get), it will recreate the _exp property in the body as an ISO-8601 only if the query string includes show_exp=true .

Supported formats for the incoming _exp value:
- JSON number.  Will be treated as a Couchbase Server expiry value (ttl in second when less than 30 days, unix time when greater)
- JSON string (numeric format) - same as JSON number
- JSON string (as ISO-8601 date).  Converted to Couchbase server expiry value.
- JSON null.  Sets expiry to zero (no expiry)

Note that subsequent updates to the document will use the expiry value on the update.  If no expiry value is set on a new revision of a document that was previously set to expire, the new version of the document will have no expiry set.

Fixes #1823

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1881)

### CODE REVIEW

**Comment by ajres** [comment]
Is there any way this will generate conflicts, clients will be adding "_exp" which will be stripped by SG before storing and may or may not be returned in subsequent GET/bulk_get depending on show_exp=true query param? I can't remember if rev-ids are opaque and not validated against the doc body by receiving clients.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-:-KKUxjeaNwmaXl0H39tD:-937558489)_

**Comment by ajres** [comment]
_[base/util.go, line 267 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-KKipajD7_VfWbtO7sav:-KKipajD7_VfWbtO7saw:1403758428) ([raw file](https://github.com/couchbase/sync_gateway/blob/5e1baae64c912221eebfe008121bd8b1b63660d9/base/util.go#L267)):_

> ``` Go
> //formatted as required by CBS expiry processing
> func DurationToCbsExpiry(ttl time.Duration) int {
>   if ttl <= time.Duration(kMaxDeltaTtl)*time.Second {
> ```

Not sure if the compiler is smart enough to see that this function always returns the same constant value. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881)_

**Comment by ajres** [comment]
_[rest/api_test.go, line 2403 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-KKjD_OXTS4cbsmGz-qL:-KKjD_OXTS4cbsmGz-qM:1886220375) ([raw file](https://github.com/couchbase/sync_gateway/blob/5e1baae64c912221eebfe008121bd8b1b63660d9/rest/api_test.go#L2403)):_

> ``` Go
>   bulkGetDocs := `{"docs": [{"id": "expNumericTTL", "rev": "1-ca9ad22802b66f662ff171f226211d5c"}]}`
>   response = rt.sendRequest("POST", "/db/_bulk_get", bulkGetDocs)
>   assertStatus(t, response, 200)
> ```

Shouldn't the _exp property be tested here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881)_

**Comment by ajres** [comment]
_[rest/api_test.go, line 2407 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-KKjDkYAYaYPLxBtkCg_:-KKjDkYB6XeAbO_VVqnP:1886220375) ([raw file](https://github.com/couchbase/sync_gateway/blob/5e1baae64c912221eebfe008121bd8b1b63660d9/rest/api_test.go#L2407)):_

> ``` Go
>   response = rt.sendRequest("POST", "/db/_bulk_get?show_exp=true", bulkGetDocs)
>   assertStatus(t, response, 200)
> ```

Shouldn't the _exp property be tested here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881)_

**Comment by ajres** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881)_

**Comment by adamcfraser** [comment]
Reviewed w/ Andy and resolved most of the questions - will also sync up w/ Jens when he's back.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[base/util.go, line 267 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-KKipajD7_VfWbtO7sav:-KKjWkhl5bneQB3u49v4:-1954197462) ([raw file](https://github.com/couchbase/sync_gateway/blob/5e1baae64c912221eebfe008121bd8b1b63660d9/base/util.go#L267)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> Not sure if the compiler is smart enough to see that this function always returns the same constant value. 
> </details>
> I was trying to avoid defining both kMaxDeltaTtl and kMaxDeltaTtlDuration, but you might be right - I'll move it to it's own const. 

---

_[rest/api_test.go, line 2403 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-KKjD_OXTS4cbsmGz-qL:-KKjWabux3xLV7dbctYO:1439108111) ([raw file](https://github.com/couchbase/sync_gateway/blob/5e1baae64c912221eebfe008121bd8b1b63660d9/rest/api_test.go#L2403)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> Shouldn't the _exp property be tested here
> </details>
> Had left out because of problems parsing multipart response.  Have added a simple strings.Contains to look for _exp in the response.

---

_[rest/api_test.go, line 2407 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-KKjDkYAYaYPLxBtkCg_:-KKjWiozxCOuHt2PA2KB:1439108111) ([raw file](https://github.com/couchbase/sync_gateway/blob/5e1baae64c912221eebfe008121bd8b1b63660d9/rest/api_test.go#L2407)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> Shouldn't the _exp property be tested here
> </details>
> Had left out because of problems parsing multipart response.  Have added a simple strings.Contains to look for _exp in the response.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881#-:-KKjXjM12emYDzfEHf49:-1716770963)_

**Comment by ajres** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1881)_

**Pull request merged**
