### PR TITLE
Feature/issue 1865

### LINKED ISSUE #1865: One shot replication of granting access doc can lead to miss documents
Hello,

When you one shot a granting access document you might not receive on resumed replications all documents in the channel since channel exists. This issue is critical. For one who might asked, we do a one shot replication because of issue https://github.com/couchbase/sync_gateway/issues/1720#issuecomment-214552671
I can send full logs in pivate mode.
As a side note, although I have no evidence of it, this might also happen without the one shot replication. We did observed in the past such missing doc issue while not using yet the one shot for granting documents.

In substance when the channel change notification is arriving after the user reload  function on the one shot replication feed, the information saying that this channel is new to the user is lost for ever.
In file db.changes.go
func (db *Database) SimpleMultiChangesFeed(chans base.Set, options ChangesOptions) (<-chan *ChangeEntry, error) {
..
waitForChanges
..
// if notifications on channel changes are already arrived it is ok, otherwise BOOM, no change found
userChangeCount, addedChannels, err = db.checkForUserUpdates(userChangeCount, changeWaiter, to)

Extract from logs (SG 1.2.0 with a few additional traces):
1)   User 31dc30d3-2017-41f6-a5a5-e7c5f0e0e847 creates document -AHVbFZo38w8oZpLwHBsi_5
Line 10901: doc id:-AHVbFZo38w8oZpLwHBsi_5
    Line 10904: doc Owner_id:31dc30d3-2017-41f6-a5a5-e7c5f0e0e847
// Note the first document sequence for this channel 26998
    Line 10915: 2016-06-11T15:51:50.085Z Cache: **SAVING #26998**

2)  One shot replication of the granting document from user 0ce0266a-f159-4fd7-8f53-9ee86952809f:
// Open one shot replication (session id = 65  this is my added counter on logs, user 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12406: 2016-06-11T15:52:47.304Z Changes: MultiChangesFeed({*}, {Since:27007 Limit:0 Conflicts:true IncludeDocs:false Wait:true Continuous:false Terminator:0xc820c8f500 HeartbeatMs:300000 TimeoutMs:300000 ActiveOnly:false}) ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)

// Check accessible channels so far so good:
Line 12411: 2016-06-11T15:52:47.307Z Changes+: MultiChangesFeed: handle channel ! options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 1 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12419: 2016-06-11T15:52:47.314Z Changes+: MultiChangesFeed: handle channel 0ce0266a-f159-4fd7-8f53-9ee86952809f options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27005 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12423: 2016-06-11T15:52:47.322Z Changes+: MultiChangesFeed: handle channel MU=0ce0266a-f159-4fd7-8f53-9ee86952809f options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27005 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12427: 2016-06-11T15:52:47.323Z Changes+: MultiChangesFeed: handle channel BI=d42059482b607e73fd77184611e6795d options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27007 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)

// going in wait mode
    Line 12428: 2016-06-11T15:52:47.324Z Changes+: MultiChangesFeed waiting...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)

```
// granting document received
Line 12434: ************************************ debut INVITE ************
Line 12436: doc id:d42059482b607e73fd77184611e6795d
Line 12437: doc Channel:-AHVbFZo38w8oZpLwHBsi_5
Line 12438: doc invitedUser_id:0ce0266a-f159-4fd7-8f53-9ee86952809f
Line 12444: 2016-06-11T15:52:47.700Z CRUD+: Saving old revision "d42059482b607e73fd77184611e6795d" / "1-2054afc9e117d3549604c5cfaca477e5" (271 bytes)
// Access to channel AHVbFZo38w8oZpLwHBsi_5 granted to user 0ce0266a-f159-4fd7-8f53-9ee86952809f as expected
```

Line 12446: 2016-06-11T15:52:47.706Z Access: Doc "d42059482b607e73fd77184611e6795d" grants channel access: map[**0ce0266a-f159-4fd7-8f53-9ee86952809f:BB=-AHVbFZo38w8oZpLwHBsi_5:27008**,BI=d42059482b607e73fd77184611e6795d:27007 31dc30d3-2017-41f6-a5a5-e7c5f0e0e847:BI=d42059482b607e73fd77184611e6795d:27007]
    Line 12449: 2016-06-11T15:52:47.707Z Cache: SAVING #27008
Line 12450: 2016-06-11T15:52:47.707Z Access: Invalidate access of "0ce0266a-f159-4fd7-8f53-9ee86952809f"
Line 12453: 2016-06-11T15:52:47.708Z Auth: Saved _sync:user:0ce0266a-f159-4fd7-8f53-9ee86952809f: {"name":"0ce0266a-f159-4fd7-8f53-9ee86952809f","all_channels":null,"sequence":27004,"passwordhash_bcrypt":"JDJhJDEwJFJIYnlCd0tTOHJtNXZ5SjJKV3JYUC5XcFd6bTJsRTUwSzJZNW8xam4xM3VTYlB4TWN5Vk5l","explicit_roles":{"public":27004},"rolesSince":{"public":27004}}
Line 12454: 2016-06-11T15:52:47.785Z Access: Computed channels for "0ce0266a-f159-4fd7-8f53-9ee86952809f": !:1,0ce0266a-f159-4fd7-8f53-9ee86952809f:27005,BB=-AHVbFZo38w8oZpLwHBsi_5:27008,BI=d42059482b607e73fd77184611e6795d:27007,MU=0ce0266a-f159-4fd7-8f53-9ee86952809f:27005

```
// Access channels under recomputation
Line 12459: 2016-06-11T15:52:48.021Z Changes+: Notifying that "xxxx" changed (keys="{*, BI=d42059482b607e73fd77184611e6795d}") count=21

// and of wait, computing changes, **NO CHANGE FOUND YET** reloading user found no changes in channels… (this skipped trace was added in code)
Line 12461: 2016-06-11T15:52:48.021Z Changes+: MultiChangesFeed reloading user skipped newcount is 18, userCount is 18   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)

// The notification on the change on the channel is now taking place but AFTER RELOAD ends
**Line 12488: 2016-06-11T15:52:48.026Z Changes+: Notifying that "xxxx" changed (keys="{_sync:user:0ce0266a-f159-4fd7-8f53-9ee86952809f}") count=22**
Line 12527: 2016-06-11T15:52:48.041Z Changes+: MultiChangesFeed: handle channel MU=0ce0266a-f159-4fd7-8f53-9ee86952809f options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27005 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12532: 2016-06-11T15:52:48.042Z Changes+: MultiChangesFeed: handle channel ! options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 1 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12537: 2016-06-11T15:52:48.046Z Changes+: MultiChangesFeed: handle channel BI=d42059482b607e73fd77184611e6795d options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27007 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12542: 2016-06-11T15:52:48.047Z Changes+: MultiChangesFeed: handle channel 0ce0266a-f159-4fd7-8f53-9ee86952809f options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x697f, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820c8f500), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27005 ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)

// One shot replication finished
```

Line 12544: 2016-06-11T15:52:48.049Z Changes: MultiChangesFeed done, reason is Continuous %!d(bool=false), sentSomething %!d(bool=true) ...   (to 65 0ce0266a-f159-4fd7-8f53-9ee86952809f)

```
// New replication starts
Line 12550: 2016-06-11T15:52:48.288Z Changes: MultiChangesFeed({*}, {Since:27008 Limit:0 Conflicts:true IncludeDocs:false Wait:true Continuous:false Terminator:0xc821469bc0 HeartbeatMs:300000 TimeoutMs:300000 ActiveOnly:false}) ...   (to 71 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12555: 2016-06-11T15:52:48.292Z Changes+: MultiChangesFeed: handle channel ! options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6980, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821469bc0), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 1 ...   (to 71 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12559: 2016-06-11T15:52:48.294Z Changes+: MultiChangesFeed: handle channel 0ce0266a-f159-4fd7-8f53-9ee86952809f options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6980, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821469bc0), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27005 ...   (to 71 0ce0266a-f159-4fd7-8f53-9ee86952809f)
```

// Here is the ISSUE: newly channel created get a start sequence set to 27008!!! Document with start sequence 26998 will never be sent….
    Line 12563: 2016-06-11T15:52:48.298Z Changes+: MultiChangesFeed: handle channel **BB=-AHVbFZo38w8oZpLwHBsi_5** options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, *\* #Seq:0x6980**, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821469bc0), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is *_27008** ...   (to 71 0ce0266a-f159-4fd7-8f53-9ee86952809f)

```
Line 12567: 2016-06-11T15:52:48.298Z Changes+: MultiChangesFeed: handle channel BI=d42059482b607e73fd77184611e6795d options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6980, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821469bc0), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27007 ...   (to 71 0ce0266a-f159-4fd7-8f53-9ee86952809f)
Line 12571: 2016-06-11T15:52:48.301Z Changes+: MultiChangesFeed: handle channel MU=0ce0266a-f159-4fd7-8f53-9ee86952809f options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6980, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821469bc0), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27005 ...   (to 71 0ce0266a-f159-4fd7-8f53-9ee86952809f)
    Line 12576: 2016-06-11T15:52:48.306Z Changes+: MultiChangesFeed waiting...   (to 71 0ce0266a-f159-4fd7-8f53-9ee86952809f)
```

3)  The exact same scenario with user ff83e059-12f0-4d24-b30d-db6dab317c78 but this time the channel notification gets sent before the user reload and channel is handled correctly
Line 13584: 2016-06-11T15:54:10.476Z Changes: MultiChangesFeed({_}, {Since:27014 Limit:0 Conflicts:true IncludeDocs:false Wait:true Continuous:false Terminator:0xc821c76000 HeartbeatMs:300000 TimeoutMs:300000 ActiveOnly:false}) ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13592: 2016-06-11T15:54:10.482Z Changes+: MultiChangesFeed: handle channel MU=ff83e059-12f0-4d24-b30d-db6dab317c78 options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27012 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13596: 2016-06-11T15:54:10.491Z Changes+: MultiChangesFeed: handle channel BI=368b028f4a0e91576a8e50cf0f4abcca options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27014 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13600: 2016-06-11T15:54:10.492Z Changes+: MultiChangesFeed: handle channel ff83e059-12f0-4d24-b30d-db6dab317c78 options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27012 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13605: 2016-06-11T15:54:10.492Z Changes+: MultiChangesFeed: handle channel ! options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 1 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13606: 2016-06-11T15:54:10.493Z Changes+: MultiChangesFeed waiting...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13612: *_*********************************\* debut INVITE ************
    Line 13614: doc id:368b028f4a0e91576a8e50cf0f4abcca
    Line 13615: doc xxxChannel:-AHVbFZo38w8oZpLwHBsi_5

```
Line 13622: 2016-06-11T15:54:10.803Z CRUD+: Saving old revision "368b028f4a0e91576a8e50cf0f4abcca" / "1-a49528a86b6a43a553064da12b0b3ecb" (271 bytes)
Line 13627: 2016-06-11T15:54:10.804Z Cache: SAVING #27015
Line 13646: ************************************ debut xxxx *************
Line 13655: 2016-06-11T15:54:11.467Z Cache: SAVING #27016
Line 13658: ************************************ debut MESSAGE
Line 13670: 2016-06-11T15:54:11.472Z Cache: SAVING #27017
Line 13681: 2016-06-11T15:54:16.191Z Changes+: Notifying that "xxxx" changed (keys="{_sync:user:ff83e059-12f0-4d24-b30d-db6dab317c78}") count=34
Line 13694: 2016-06-11T15:54:16.191Z Changes+: Notifying that "xxx" changed (keys="{*, BB=-AHVbFZo38w8oZpLwHBsi_5, BI=368b028f4a0e91576a8e50cf0f4abcca, ff83e059-12f0-4d24-b30d-db6dab317c78}") count=35
**Line 13697: 2016-06-11T15:54:16.192Z Changes+: Notifying that "xxx" changed (keys="{*, BB=-AHVbFZo38w8oZpLwHBsi_5}") count=36**
Line 13736: 2016-06-11T15:54:16.197Z Changes+: **New channels found after user   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78) reload: {BB=-AHVbFZo38w8oZpLwHBsi_5}**
Line 13741: 2016-06-11T15:54:16.200Z Changes+: MultiChangesFeed: handle channel MU=ff83e059-12f0-4d24-b30d-db6dab317c78 options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27012 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)

// This time the trigger by is set and makes the document search done since channel beginning
Line 13745: 2016-06-11T15:54:16.200Z Cache: getCachedChanges("BB=-AHVbFZo38w8oZpLwHBsi_5", {0 **27015** 0 0 <nil> <nil> %!d(string=) 0 0 0 %!d(string=)}) --> ** #6 changes valid from #1**
Line 13747: 2016-06-11T15:54:16.200Z Changes+: MultiChangesFeed: handle channel BB=-AHVbFZo38w8oZpLwHBsi_5 options are db.ChangesOptions{Since:db.SequenceID{SeqType:0, TriggeredBy:0x6987, LowSeq:0x0, Seq:0x0, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27015 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)

Line 13789: 2016-06-11T15:54:16.215Z Changes+: MultiChangesFeed: handle channel ! options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 1 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
Line 13805: 2016-06-11T15:54:16.218Z Changes+: MultiChangesFeed: handle channel BI=368b028f4a0e91576a8e50cf0f4abcca options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27014 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
Line 13811: 2016-06-11T15:54:16.218Z Changes+: MultiChangesFeed: handle channel ff83e059-12f0-4d24-b30d-db6dab317c78 options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6986, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc821c76000), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27012 ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)
```

//End of one shot replication  
Line 13828: 2016-06-11T15:54:16.240Z Changes: MultiChangesFeed done, reason is Continuous %!d(bool=false), sentSomething %!d(bool=true) ...   (to 92 ff83e059-12f0-4d24-b30d-db6dab317c78)

// New session  
Line 13836: 2016-06-11T15:54:16.482Z Changes: MultiChangesFeed({_}, {Since:27017 Limit:0 Conflicts:true IncludeDocs:false Wait:true Continuous:false Terminator:0xc820a571a0 HeartbeatMs:300000 TimeoutMs:300000 ActiveOnly:false}) ...   (to 98 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13840: 2016-06-11T15:54:16.489Z Changes+: MultiChangesFeed: handle channel MU=ff83e059-12f0-4d24-b30d-db6dab317c78 options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6989, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(_db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820a571a0), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27012 ...   (to 98 ff83e059-12f0-4d24-b30d-db6dab317c78)
    Line 13844: 2016-06-11T15:54:16.491Z Changes+: MultiChangesFeed: handle channel BB=-AHVbFZo38w8oZpLwHBsi_5 options are db.ChangesOptions{Since:db.SequenceID{SeqType:1, TriggeredBy:0x0, LowSeq:0x0, Seq:0x6989, Clock:base.SequenceClock(nil), TriggeredByClock:base.SequenceClock(nil), ClockHash:"", SequenceHasher:(*db.sequenceHasher)(nil), vbNo:0x0, TriggeredByVbNo:0x0, LowHash:""}, Limit:0, Conflicts:true, IncludeDocs:false, Wait:false, Continuous:false, Terminator:(chan bool)(0xc820a571a0), HeartbeatMs:0x493e0, TimeoutMs:0x493e0, ActiveOnly:false} seAdded is 27015 ...   (to 98 ff83e059-12f0-4d24-b30d-db6dab317c78)
…

### PR DESCRIPTION
**Pull request by adamcfraser**
Build verification only - not intended for merge yet.

Fixes #1865.

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/2062)

### CODE REVIEW

**Comment by keimoon** [comment]
When will this PR be merged? We rely on this fix for our product.

**Comment by Crapulax** [comment]
Keimoon, Adam,

I would be interested to check if your scenario is corrected by the fix I did (see #2117 ). If Couchbase (Adam) is fine, as I do not want to bypass them, I can send you Ubuntu test binary or source code. I there is still an issue I would analyze logs.

Let me know,
Steve.

**Comment by keimoon** [comment]
We are currently using this PR in our server and it works fine. We also use Couchbase as backend.

**Comment by adamcfraser** [comment]
Merged as #2211.

**Pull request closed without merging**
