### PR TITLE
Remove duplicate doc retrieval during changes w/ include_docs

### PR DESCRIPTION
**Pull request by adamcfraser**

### CODE REVIEW

**Comment by tleyden** [comment]
Related to https://github.com/couchbase/sync_gateway/issues/2428

**Comment by tleyden** [comment]
LGTM.  Actually looking at the PR for https://github.com/couchbase/sync_gateway/issues/2428, it wasn't doing the double-get at that point either.  https://github.com/couchbase/sync_gateway/blob/aa2bcad6e0e86704e214dd7615cd4ba268d39bb5/db/changes.go#L77-L110

So it looks like it was added later somehow.  I don't know if it's worth digging into.

**Comment by adamcfraser** [comment]
Maybe a bad merge in https://github.com/couchbase/sync_gateway/pull/2531

Want to check that merge to see if there's anything else unexpected?

**Comment by tleyden** [comment]
Nothing else looks bad .. it was mostly additive

**Pull request merged**
