### PR TITLE
Fixes issue #2523 Sync Gateway should gracefully handle TAP being unavailable

### PR DESCRIPTION
**Pull request by tleyden**
Fixes issue #2523 
Fixes issue #2459

Integration tests:

- http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/265/
- http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/266/

### CODE REVIEW

**Comment by adamcfraser** [comment]
Can we include the handling for the related issue https://github.com/couchbase/sync_gateway/issues/2459 in this PR?

**Comment by tleyden** [comment]
> Can we include the handling for the related issue #2459 in this PR?

Done -- see https://github.com/couchbase/sync_gateway/pull/2883/commits/de622f352878d17cfe1e735ae37b34ed63e63cd1

**Comment by tleyden** [comment]
Integration test 265 failed with error:

```
ERROR: No artifacts found that match the file pattern "*.html, *.log". Configuration error?
ERROR: ‘*.html’ doesn’t match anything, but ‘cbbuild/scripts/html/*.html’ does. Perhaps that’s what you mean?
```

I updated the jenkins job to set the flag: 

screen shot 2017-09-06 at 5 00 09 pm

Which should fix it.  Otherwise looks like that run succeeded.

**Comment by tleyden** [comment]
Kicked off new integration tests after https://github.com/couchbase/sync_gateway/commit/de622f352878d17cfe1e735ae37b34ed63e63cd1


http://uberjenkins.sc.couchbase.com/job/build-sync-gateway/267/
http://uberjenkins.sc.couchbase.com/job/build-sync-gateway/268/

**Pull request merged**
