### PR TITLE
run git fetch to avoid "fatal: reference is not a tree" errors

### PR DESCRIPTION
**Pull request by tleyden**
Ran into another snag with this ..

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1820)

### CODE REVIEW

**Comment by tleyden** [comment]
@sethrosetter this change is related to https://github.com/couchbase/sync_gateway/commit/381d46ee19c8b304baf4c1dbcfcfecd0a64df0ce

Feel free to review that code as well (and would be great if you could try the README instructions!)

**Comment by sethrosetter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[tools/manifest-helper, line 88 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820#-KJI9FVXPTNMwA6NDa34:-KJI9FVXPTNMwA6NDa35:-1967094900) ([raw file](https://github.com/couchbase/sync_gateway/blob/02582c61fd83b55473ca3983369b301d1805fd67/tools/manifest-helper#L88)):_

> ```
>     # run git fetch to avoid "fatal: reference is not a tree" errors
>     print("git fetch in {}".format(path))
>     output = subprocess.check_output(
> ```

Did you want this to fail on non-zero exit? If so, you would want to use `check_call`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820)_

**Comment by sethrosetter** [comment]
seeing the following warnings:
`WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/couchbase/retriever`
`WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/natefinch/npipe`
`WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/tleyden/fakehttp`
`WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/golang.org/x/sys`
`WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/kardianos/service`
`WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/kardianos/osext`

Are these expected?

<details><summary>

<i>Previously, tleyden (Traun Leyden) wrote…</i></summary>



> @sethrosetter this change is related to https://github.com/couchbase/sync_gateway/commit/381d46ee19c8b304baf4c1dbcfcfecd0a64df0ce
> 
> Feel free to review that code as well (and would be great if you could try the README instructions!)
> </details>

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820#-:-KJIEycU-6lVWhVlsJRs:-771060349)_

**Comment by sethrosetter** [comment]
After the manifest helper checks out the commits, does it do a rebuild of the sync_gateway binary?

<details><summary>

<i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>



> seeing the following warnings:
> `WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/couchbase/retriever`
> `WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/natefinch/npipe`
> `WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/tleyden/fakehttp`
> `WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/golang.org/x/sys`
> `WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/kardianos/service`
> `WARN: Directory does not exist, skipping: /Users/sethrosetter/go/src/github.com/kardianos/osext`
> 
> Are these expected?
> 
> </details>

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820#-:-KJIHkPkAtVL_0lC3d1F:973228926)_

**Comment by tleyden** [comment]
Nope .. the manifest helper just shows/changes what commit a dependency repo is checked out as

<details><summary>

<i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>



> After the manifest helper checks out the commits, does it do a rebuild of the sync_gateway binary?
> </details>

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820#-:-KJIuAwBi3oL9l5APcSR:-711788677)_

**Comment by tleyden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[tools/manifest-helper, line 88 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820#-KJI9FVXPTNMwA6NDa34:-KJIuL0Jzd_bK3FJTr93:-1240871041) ([raw file](https://github.com/couchbase/sync_gateway/blob/02582c61fd83b55473ca3983369b301d1805fd67/tools/manifest-helper#L88)):_
<details><summary>

<i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>



> Did you want this to fail on non-zero exit? If so, you would want to use `check_call`
> </details>
> Are you sure?  I saw it fail and things would "blow up" on non-zero exits.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820)_

**Comment by sethrosetter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[tools/manifest-helper, line 88 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820#-KJI9FVXPTNMwA6NDa34:-KJIvbj0bbBw4Y3b8WUI:440691541) ([raw file](https://github.com/couchbase/sync_gateway/blob/02582c61fd83b55473ca3983369b301d1805fd67/tools/manifest-helper#L88)):_
<details><summary>

<i>Previously, tleyden (Traun Leyden) wrote…</i></summary>



> Are you sure?  I saw it fail and things would "blow up" on non-zero exits.
> </details>
> Oh nevermind. `check_output` checks error and returns output, whereas `check_call` just checks for non-zero error code

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1820)_

**Pull request merged**
