### PR TITLE
Fixes #2024 sg_collectinfo: test upload with large (2 GB) files

### LINKED ISSUE #2024: sg_collectinfo: test upload with large (2 GB) files
Since using pure python, streaming upload might be an issue

### PR DESCRIPTION
**Pull request by tleyden**
This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/2025)

### CODE REVIEW

**Comment by tleyden** [comment]
Fixes #2024

**Comment by tleyden** [comment]
@ajres I guess we'll have to merge to master before you could test on Windows?

**Comment by ajres** [comment]
I don't know any other way to generate the installer.

**Comment by ajres** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2025)_

**Pull request merged**
