### PR TITLE
Fixes #3411 Convert CouchbaseBucketGoCB method receivers to pointer r…

### LINKED ISSUE #3411: Convert CouchbaseBucketGoCB method receivers to pointer receivers
During the effort for the https://github.com/couchbase/sync_gateway/issues/3389, I hit a snag while trying to add a [test helper method](https://github.com/couchbase/sync_gateway/commit/1c5a0fb0c01ae01c2af9c89f332a06894e462441#diff-c6b9f50555be165960fa00d4c360bfe3R2207) and had to do [clunky](https://github.com/couchbase/sync_gateway/commit/1c5a0fb0c01ae01c2af9c89f332a06894e462441#diff-c6b9f50555be165960fa00d4c360bfe3R2076) [workarounds](https://github.com/couchbase/sync_gateway/commit/1c5a0fb0c01ae01c2af9c89f332a06894e462441#diff-f494338fe77eff0d93e32db8d4b11c8cR653) to get past the compiler errors.

For this and efficiency reasons to reduce memory copying, it's better to convert these into pointer receivers.

It should be a separate PR to reduce scope and run separate integration tests.

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #3411

### CODE REVIEW

**Comment by tleyden** [comment]
Integration tests:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/464/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/465/

**Comment by tleyden** [comment]
Integration tests on dev branch (for comparison purposes):

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/466/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/467/

**Comment by tleyden** [comment]
Failing test in http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/464/

```
_time=2018-04-03T15:47:26.762-07:00 _level=INFO _msg=Using plain authentication for user test_data_bucket 
2018-04-03T15:47:26.859-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:bernard}") count=2
2018-04-03T15:47:26.862-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:bernard}") count=3

	database_test.go:1160
	assert.DeepEquals(t, user.Channels(), expected)	

	expected: channels.TimedSet{"ABC":channels.VbSequence{VbNo:(*uint16)(0xc42021d198), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}}
	     got: channels.TimedSet{"ABC":channels.VbSequence{VbNo:(*uint16)(0xc42021ced0), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}}
2018-04-03T15:47:27.306-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:bernard}") count=4
2018-04-03T15:47:27.308-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:bernard}") count=5

	database_test.go:1170
	assert.DeepEquals(t, user.Channels(), expected)	

	expected: channels.TimedSet{"NBC":channels.VbSequence{VbNo:(*uint16)(0xc42037e51a), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc42037e518), Sequence:0x1}}
	     got: channels.TimedSet{"NBC":channels.VbSequence{VbNo:(*uint16)(0xc4201e98c0), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc42037e206), Sequence:0x1}}
2018-04-03T15:47:27.482-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:bernard}") count=6
2018-04-03T15:47:27.482-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:bernard}") count=7

	database_test.go:1181
	assert.DeepEquals(t, user.Channels(), expected)	

	expected: channels.TimedSet{"PBS":channels.VbSequence{VbNo:(*uint16)(0xc42037f680), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc42037f66c), Sequence:0x1}, "NBC":channels.VbSequence{VbNo:(*uint16)(0xc42037f66e), Sequence:0x1}}
	     got: channels.TimedSet{"!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc42037f44e), Sequence:0x1}, "NBC":channels.VbSequence{VbNo:(*uint16)(0xc42037f450), Sequence:0x1}, "PBS":channels.VbSequence{VbNo:(*uint16)(0xc42021dfd4), Sequence:0x1}}
2018-04-03T15:47:27.646-07:00 Changes+: changeListener.Stop() called
2018-04-03T15:47:27.646-07:00 WARNING: Error closing GoCB bucket: connection shut down. -- base.(*CouchbaseBucketGoCB).Close() at bucket_gocb.go:2110
--- FAIL: TestAccessFunctionWithVbuckets (3.03s)
	assert.go:31: 
	assert.go:31: 
	assert.go:31: 
```

**Comment by tleyden** [comment]
Fails locally against CBS running on linux with:

```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/tleyden/Development/sync_gateway/godeps #gosetup
/usr/local/go/bin/go test -c -i -o /private/var/folders/l7/hr7n2gb52nz0vn9lq_x2prcr0000gn/T/___TestAccessFunctionWithVbuckets_in_database_test_go github.com/couchbase/sync_gateway/db #gosetup
/private/var/folders/l7/hr7n2gb52nz0vn9lq_x2prcr0000gn/T/___TestAccessFunctionWithVbuckets_in_database_test_go -test.v -test.run ^TestAccessFunctionWithVbuckets$ #gosetup
2018-04-03T16:34:09.937-07:00 NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2018-04-03T16:34:09.937-07:00 NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2018-04-03T16:34:14.758-07:00 WARNING: TestBucketManager.EmptyBucket(): still 1 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:349
2018-04-03T16:34:15.266-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://couchbase-server:8091> as user "test_data_bucket"
2018-04-03T16:34:15.595-07:00 Design docs successfully created for view version 2.0.
2018-04-03T16:34:15.597-07:00 Initializing changes cache for database db with sequence: 0
2018-04-03 16:34:15.627733 I | bucketDataSource.Start() called
_time=2018-04-03T16:34:15.682-07:00 _level=INFO _msg=Using plain authentication for user test_data_bucket 

	database_test.go:1160
	assert.DeepEquals(t, user.Channels(), expected)	

	expected: channels.TimedSet{"Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc420490078), Sequence:0x1}}
	     got: channels.TimedSet{"!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc420515c20), Sequence:0x1}}

	database_test.go:1170
	assert.DeepEquals(t, user.Channels(), expected)	

	expected: channels.TimedSet{"NBC":channels.VbSequence{VbNo:(*uint16)(0xc4202c36aa), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc4202c36a8), Sequence:0x1}}
	     got: channels.TimedSet{"Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc4202c2e46), Sequence:0x1}, "NBC":channels.VbSequence{VbNo:(*uint16)(0xc4202c3028), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}}

	database_test.go:1181
2018-04-03T16:34:16.897-07:00 WARNING: Error closing GoCB bucket: connection shut down. -- base.(*CouchbaseBucketGoCB).Close() at bucket_gocb.go:2135
2018-04-03 16:34:16.897661 I | bucketDataSource.Close() called
2018-04-03T16:34:16.897-07:00 WARNING: changeCache: Error unmarshaling doc "_sync:user:bernard": Attempt to unmarshal principal using closed bucket -- base.WarnR() at logging.go:525
2018-04-03T16:34:16.897-07:00 WARNING: Error processing DCP stream - will attempt to restart/reconnect if appropriate: pkt.Receive, err: read tcp 172.28.128.1:53768->172.28.128.3:11210: use of closed network connection. -- base.(*DCPReceiver).OnError() at dcp_feed.go:137
	assert.DeepEquals(t, user.Channels(), expected)	

	expected: channels.TimedSet{"PBS":channels.VbSequence{VbNo:(*uint16)(0xc42049128c), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc420491288), Sequence:0x1}, "NBC":channels.VbSequence{VbNo:(*uint16)(0xc42049128a), Sequence:0x1}}
	     got: channels.TimedSet{"PBS":channels.VbSequence{VbNo:(*uint16)(0xc420490df4), Sequence:0x1}, "!":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "Netflix":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x1}, "ABC":channels.VbSequence{VbNo:(*uint16)(0xc420490b9e), Sequence:0x1}, "NBC":channels.VbSequence{VbNo:(*uint16)(0xc420490ba0), Sequence:0x1}}
	assert.go:31: 
	assert.go:31: 
	assert.go:31: 

Process finished with exit code 1

```

**Comment by tleyden** [comment]
Re-run integration tests with [failing test](https://github.com/couchbase/sync_gateway/issues/3413) disabled:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/468/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/469/

**Comment by tleyden** [comment]
> Re-run integration tests with failing test disabled:

These passed.

@adamcfraser I think this should be ready to merge

**Review by adamcfraser — APPROVED** [review]

**Pull request merged**
