### PR TITLE
convert references from walrus to sgbucket

### PR DESCRIPTION
**Pull request by jchris**
Based on conversation with @adamcfraser I think this aligns with an ongoing refactor.

### CODE REVIEW

**Comment by tleyden** [comment]
Can you look into this first?  https://drone.io/github.com/couchbaselabs/walrus/20

**Comment by jchris** [comment]
Totally

**Comment by jchris** [comment]
It's fixed. Sorry about working on walrus master, tracking all these submodules is hard.

**Comment by tleyden** [comment]
One more ask -- can you kick off a jenkins build for this sync gw branch?  (if you need help, let me know)

**Comment by tleyden** [comment]
Btw this branch should be named feature/walrus_cleanup

**Comment by tleyden** [comment]
Kicking off jenkins builds: https://github.com/couchbase/sync_gateway/wiki/Viewing-Running-Jenkins-builds

**Comment by jchris** [comment]
Build passed http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/270/

**Pull request merged**
