### PR TITLE
Feature/distributed index 1289 gocb timeouts

### PR DESCRIPTION
**Pull request by tleyden**
Performance test results:  https://github.com/couchbase/sync_gateway/issues/1289#issuecomment-160775984

Functional test results: https://github.com/couchbase/sync_gateway/issues/1289#issuecomment-161897154

### CODE REVIEW

**Comment by tleyden** [comment]
Hold off on merging this PR until https://github.com/couchbase/sync_gateway/issues/1289#issuecomment-162597433 is resolved.

**Comment by tleyden** [comment]
@adamcfraser 

Follow up to our conversation, I was misinterpreting the behavior a bit due to the fact that if a `RetryWorker` returns an error, it will immediately abort the retry loop, regardless of the `finished` value returned by the worker, due to this code:

```
func RetryLoop(worker RetryWorker, sleeper RetrySleeper) (error, interface{}) {

    numAttempts := 1

    for {
        workerFinished, err, value := worker()
        if err != nil {
            return err, nil
        }
                ...
```

So for example this code:

```
        newCas, err := bucket.Bucket.Replace(k, v, gocb.Cas(cas), uint32(exp))
        // TODO: on a cas error, no need to retry either
        if err == nil {
            finished = true
        } else {
            finished = isNotFoundError(err)
        }
        return finished, err, uint64(newCas)
```

For the "TODO" comment, no change is actually needed to make this work, since in the case of a CAS error, it will currently return an error and break out of the retry loop.  (I discovered this by writing a unit test against the existing code and being surprised that it already passed without any retries happening)

I'm going to look into making the code a bit more clear in this regard.

**Comment by tleyden** [comment]
@adamcfraser I reversed the logic and renamed the parameter from `finished` to `retryUnlessError`.  See https://github.com/couchbase/sync_gateway/commit/ecbff9667f06f1acabfcfcc175b4d47c074baa44

**Comment by tleyden** [comment]
@adamcfraser Made the changes, see https://github.com/couchbase/sync_gateway/commit/9b109072be66323252c9e115c73ba53ee43673d0

If you think this is ready to merge, I will squash it into a single commit and re-push.

**Comment by tleyden** [comment]
@adamcfraser do you think it's worth to try figure out _why_ we are seeing this warning in the logs?

```
2015-12-04T18:08:30.675-08:00 WARNING: Error writing sharded clock partition [%!d(string=_idx_c:_idx_stableSeq:clock-15)]:Key already exists. -- base.func·043() at sharded_sequence_clock.go:131
```

You mentioned that you didn't expect to see that unless multiple index writers were servicing the same DCP stream shards.

**Comment by adamcfraser** [comment]
I spent some time reviewing test output w/ Seth yesterday and wasn't able to get to the bottom of it.  It didn't look like multiple nodes writing to the doc - it appears to be internal to a single SG node (i.e. potentially multiple goroutines trying to write to the block).  I was planning to revisit when looking into https://github.com/couchbase/sync_gateway/issues/1339.

**Comment by tleyden** [comment]
Ok.  You are pretty sure it's not related to the changes on this branch though?

**Comment by tleyden** [comment]
I tried to compare against the `distributed_index` branch, and did not see those errors

```
python provision/install_sync_gateway.py --branch=feature/distributed_index && python -m pytest --capture=no functional_tests/test_users_channels.py::test_single_user_multiple_channels
```

(I have three SG's setup as index writers, and no non-writers)

I didn't see that error: [gist logs with grep for error](https://gist.github.com/tleyden/2bfde15b52e5d50d8e23)

Will retry identical setup with the feature/distributed_index_1289_gocb_timeouts branch.

**Comment by tleyden** [comment]
Reproduced a Sync Gw panic on two nodes when running:

```
python provision/install_sync_gateway.py --branch=feature/distributed_index_1289_gocb_timeouts && python -m pytest --capture=no functional_tests/test_users_channels.py::test_single_user_multiple_channels
```

https://gist.github.com/tleyden/cc5750fa0a1ce97dcde4

**Comment by tleyden** [comment]
Full log files from that run:
- https://gist.github.com/tleyden/08836fb0bf9d070c1c9a
- https://gist.github.com/367ac6412e3dc71a4c85
- https://gist.github.com/c0863ab773a516de2f09

**Comment by tleyden** [comment]
> Reproduced a Sync Gw panic on two nodes when running

Fixed in:

https://github.com/couchbase/sync_gateway/commit/b5ca127ab93b42c65a86c9bd3d7c8fc754866dbf

Functional test passing:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/152/console

@sethrosetter the ability to run a single functional test was really useful!

**Comment by tleyden** [comment]
Still seeing failures when running all the functional tests:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/153/

**Comment by tleyden** [comment]
Disregard last comment, that was running ALL tests rather than `distributed_index`, so those failures were to be expected.  Re-running.

**Comment by tleyden** [comment]
Ok the full functional test suite passed:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/157/

(I branched sync-gateway-testcluster and disabled the 4 known failing tests, so this would go faster)

**Comment by tleyden** [comment]
@adamcfraser any thoughts on leaving this code in for future debugging purposes?

https://github.com/couchbase/sync_gateway/commit/f888ae505fd67066025f4217c19a9f8707da45da

**Pull request closed without merging**
