### PR TITLE
Fixes #3249 RunTime error , nil pointer deference error in DI mode

### LINKED ISSUE #3249: RunTime error , nil pointer deference error in DI mode
### Sync Gateway version
2.0.0-759

### Operating system
Centos
###  SG Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "allow_conflicts": false,
            "revs_limit": 5,
            "channel_index":{
                "num_shards":16,
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket",
                "username":"index-bucket",
                "password": "password",
                "writer":false
            }
        }
    }
}

```
###  SG Accel Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "allow_conflicts": false,
            "revs_limit": 5,
            "channel_index":{
                "num_shards":16,
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket",
                "username":"index-bucket",
                "password": "password",
                "writer":true
            }
        }
    }
}


```
### Log output
https://gist.github.com/sridevi-15/a8dd8d50d121368da96ac683380e8e3b

### Steps to reproduce
1.  Set up SG with sg accel
2.  Create docs in CBL,
3.  Start replication with continous true and push_pull
4. update docs in SG and CBL concurrently by running `pytest -rsx -s -k test_get_set_pinnnedServerCertificates --server-version=5.0.0 --sync-gateway-version=2.0.0-759 --mode=cc --liteserv-host=192.168.0.104 --liteserv-port=8080 --xattrs  --create-db-per-test=pull-test  --skip-provisioning --liteserv-platform=ios testsuites/CBLTester/CBL_Functional_tests/`
5. Wait for replicator to be idle

### Expected behavior
Replication should complete and all docs should replicated in SG and CBL

### Actual behavior
CBL got an error 'Connection reset by Peer'
It throw an error on sg logs

### Link to the test code : 
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L953

### Additional information : 
CBL logs . : https://gist.github.com/sridevi-15/a3402ff18c4837ff5e365471d5bdf463
Note : This error happening with ios build 565 : http://latestbuilds.service.couchbase.com/builds/latestbuilds/couchbase-lite-ios/2.0.0/565/

but I did not see this issue with 560

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #3249 

- Remove call to `ParseSequenceIDFromJSON()` since it does not use the correct `SequenceHasher`.  Replace with call to `bh.db.ParseSequenceID()`, which has db context and uses correct `SequenceHasher`
- Remove unused `ParseSequenceIDFromJSON()`

### CODE REVIEW

**Comment by tleyden** [comment]
Integration tests:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/338/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/339/

**Comment by tleyden** [comment]
@sridevi-15 retested the pre-cleanup fix and said that the test is passing now.   I have sent her the post-cleanup fix (with debugging info removed) to do one more retest

**Review by adamcfraser — APPROVED** [review]
Looks good.

**Comment by tleyden** [comment]
I just realized I forgot to move over this call to the cleanup branch:

```
			since = bh.db.CreateZeroSinceValue()
```

Re-pushed an amended commit

**Comment by tleyden** [comment]
Pushed new commit: https://github.com/couchbase/sync_gateway/pull/3256/commits/2c36c764508f7ab20f293c3245533a4bd3827f2c

**Review by adamcfraser — APPROVED** [review]

**Pull request merged**
