### PR TITLE
Rename to match target naming of binary

### PR DESCRIPTION
**Pull request by tleyden**
This is confusing because the build machine is currently ingesting index_writer and renaming to sg-accel, which is super confusing.  @sethrosetter ran into this issue. 

After merge, re-assign to @michaelkwok to fix build scripts after merge.

### CODE REVIEW

**Comment by tleyden** [comment]
@adamcfraser I renamed this to sg_accel

**Comment by tleyden** [comment]
@michaelkwok can you update your packaging scripts to expect binary name `sg_accel` rather than `index_writer`?

**Comment by michaelkwok** [comment]
I have updated the build to align with the new name sg_accel

**Comment by tleyden** [comment]
@michaelkwok can you drop a link to your commit(s)?

**Comment by michaelkwok** [comment]
In the previous commit, I changed the packaging to derive the name from the parameters passed in by the build script.  So I only had to update my build script with the new name for this change.

**Comment by tleyden** [comment]
Fixed in https://github.com/couchbase/build/commit/ffaf1a44cd4c72c8bae042cf2eff5a9cadec6039

**Comment by michaelkwok** [comment]
Fixed in couchbase/build@ffaf1a4

**Pull request merged**
