### PR TITLE
Added sgcollect_info to Windows InstallShield project

### LINKED ISSUE #1845: Update windows installer to include sgcollect_info
For SG 1.3 sgcollect_info will be installed into a tool folder at the same level as bin

The Windows installer needs to be updated for this change also.

### PR DESCRIPTION
**Pull request by ajres**
fixes #1845 

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1909)

### CODE REVIEW

**Comment by ajres** [comment]
Closing this PR, as Install Shield is picking up and deploying the the tools folder using the current project folder structure.

**Comment by mattcarabine** [comment]
Just installed the exe produced as part of http://mobile.jenkins.couchbase.com/job/sgw-windows-build/137/ but it didn't seem to include sgcollect_info at all.

Am I doing something wrong here?

Directory structure is as follows:

```
C:\Program Files (x86)\Couchbase>dir
 Volume in drive C has no label.
 Volume Serial Number is 50B5-20F6

 Directory of C:\Program Files (x86)\Couchbase

03/07/2016  19:34    <DIR>          .
03/07/2016  19:34    <DIR>          ..
03/07/2016  19:34    <DIR>          examples
01/07/2016  12:55             2,556 LICENSE.txt
01/07/2016  12:55             1,382 README.txt
01/07/2016  11:29               230 serviceconfig.json
01/07/2016  12:55         3,475,968 sg-windows.exe
01/07/2016  12:51        22,704,128 sync_gateway.exe
01/07/2016  12:55                35 VERSION.txt
               6 File(s)     26,184,299 bytes
               3 Dir(s)     800,608,256 bytes free
```

**Comment by ajres** [comment]
Reopening, while the tools folder may be being picked up by the build process, the InstallShield will not deploy it without the new entries in the IS project files.

**Comment by mattcarabine** [comment]
Sorry to re-open this again, but went to download the .exe created as part of the build process which includes this change but cannot find the installer.

From looking at the build output it looks like something failed due to an incorrect path:

```
10:28:37 C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:1569:in `block in fu_each_src_dest': same file: c:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/couchbase/sync_gateway/build/opt/couchbase-sync-gateway//manifest.txt and .\opt\couchbase-sync-gateway/manifest.txt (ArgumentError)
10:28:37    from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
10:28:37    from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
10:28:37    from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:516:in `mv'
10:28:37    from C:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/couchbase/sync_gateway/build/package-win.rb:91:in `<main>'
10:28:37 
```

Feel free to re-open a separate issue if this wasn't caused by your change!

**Pull request merged**
