### PR TITLE
Seems unnecessary to keep `*.sublime-project` file around

### PR DESCRIPTION
**Pull request by PaulCapestany**
Removed `sync_gateway.sublime-project` file

For users of Sublime Text, this file can negatively interfere with whatever Sublime project structures and/or build systems they may have independently set up.

### CODE REVIEW

**Comment by zgramana** [comment]
@PaulCapestany both @adamcfraser and I are trying to understand your pain point, but aren't really grokking the problem. What's different about this setup that's cause it to blow yours up?

**Comment by PaulCapestany** [comment]
Nothing blows up, it's just that including the `sync_gateway.sublime-project` file can mess with people's personal Sublime project settings.

Included screenshot with how things look out-of-the-box _with_ the file (above) and _without_ the file (below):

**Comment by tleyden** [comment]
Done in https://github.com/couchbase/sync_gateway/commit/67ddc5cf91cdbcb5a71db443b365f787a0c57cda

(for a moment the github web ui was telling me I couldn't auto merge this, so I just did it in a separate commit)

**Comment by snej** [comment]
The project was deliberately organized that way to make it easy to get to the important source code without having to drill through four unnecessary layers of hierarchy (src/ github.com/ couchbase/ sync_gateway) to get to it, and to suppress top-level stuff that isn't relevant for editing.

If you didn't like the layout, you could have offered suggestions on changing it rather than just deleting the file.

And how does this interfere with other structures? If you want your own project you can create one; you don't have to open the one that's there.

(Sorry if I sound annoyed. It's because I am.)

**Comment by PaulCapestany** [comment]
@snej et al — apologies, this was an unfortunate case of PEBCAK. Turns out I have scripts that automatically setup/manage/open projects for me that I'd totally forgotten about since I've been using them so long (so much so that I could have sworn they were just default behavior in Sublime). Anyway, just realized that's why I was running into issues. My bad!

In my defense though, out of 1,000+ repos I've grabbed off Github, this is the only one that I've ever come across that actually included its own `.sublime-project` file. I'd always assumed they weren't meant to be checked-in, but apparently that just applies to `.sublime-workspace` files. Oops.

**Pull request closed without merging**
