### PR TITLE
Support for sending docs and attachments as compressed deltas

### PR DESCRIPTION
**Pull request by snej**
https://github.com/couchbaselabs/couchbase-lite-api/wiki/Delta-Compression
For #452

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/683)

### CODE REVIEW

**Comment by snej** [comment]
I suspect it'll be less confusing to review this commit-by-commit.

**Comment by snej** [comment]
Hi Adam, I've merged the branch so it's up to date. Do you have time to review it? Or do you think we should defer this feature?

**Comment by tleyden** [comment]
Kicked off a perf run: http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/840/

**Comment by tleyden** [comment]
Kicked off perf run http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/842/

**Comment by tleyden** [comment]
Results from [perf run 864](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/846/console):

```
[27/Mar/2015 14:33:00] INFO - Aggregated latency: [
    "PushToSubscriberInteractive/p95 average: 6.09 - doesn't meet the criteria of 3", 
    "PushToSubscriberInteractive/p99 average: 6.885 - doesn't meet the criteria of 5"
]
```

**Comment by snej** [comment]
@tleyden — Does the PushToSubscriberInteractive test use attachments? The code path for docs without attachments shouldn't be much affected by this patch...

**Comment by tleyden** [comment]
@snej it can be configured to use attachments, but in that perf test it was not using attachments.

Btw I should have qualified those results, I don't know if they actually represent a performance regression from the master branch this was based off of.  (for example, even the master branch this was based off of may have not been passing the performance criteria)

I know the current master branch has managed to get the latency numbers a bit lower, but the latency numbers above look like they are within reason.  @adamcfraser any thoughts?

**Comment by adamcfraser** [comment]
Yes - the PushToSubscriberInteractive numbers above are in the range of expected values on master for the user volume used in the test.  I was considering those numbers as a 'pass' for the perf test of this PR.

**Comment by snej** [comment]
Whew! I was anticipating another "fun" round of Go profiling :stuck_out_tongue_closed_eyes: 

So … does that mean the PR can be merged?

**Comment by adamcfraser** [comment]
Need memory and CPU usage analysis against the feature branch before merging to master.

**Comment by adamcfraser** [comment]
Needs to be rebased on to master, then run the standard perf regression test.  Planned for 2.0 in conjunction with client uptake.

**Comment by lgleim** [comment]
Is this still on the radar?

**Comment by K-Leon** [comment]
I would love seeing this landed - it's a great feature!

**Comment by bbrks** [comment]
Closing this PR as it's superseded by the Delta Sync work done in Iridium. This might be useful as a reference for attachment deltas in the future.

**Pull request closed without merging**
