### PR TITLE
Support running generateChanges in one-shot mode

### LINKED ISSUE #3301: Blip-sync subChanges running one-shot as continuous
subChanges is calling generateContinuousChanges, which forces continuous=true.

### PR DESCRIPTION
**Pull request by adamcfraser**
Non-continuous replications made via blip-sync will now avoid continuous processing overhead (changeWaiters, recovery from dropped client connections).

Fixes #3301

### CODE REVIEW

**Comment by adamcfraser** [comment]
Integration tests:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/403/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/404/

**Comment by adamcfraser** [comment]
Integration tests showing failures that I didn't see locally - investigating.

**Comment by adamcfraser** [comment]
Integration tests, post fixes:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/406/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/407/

**Comment by adamcfraser** [comment]
TestShadowerPush failed again on #406.  (previously seen as an intermittent failure on https://github.com/couchbase/sync_gateway/pull/3260).

**Comment by adamcfraser** [comment]
Integration tests are failing w/ timeout even when not running under race.  No obvious test issues, bumping timeout to 20m.
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/410/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/411/

**Comment by adamcfraser** [comment]
@tleyden Latest integration tests are green - ready for your review.

**Review by tleyden — APPROVED** [review]
LGTM

**Pull request merged**
