### PR TITLE
Adds support for custom token TTL via the authenticate endpoint and HTML form

### LINKED ISSUE #1847: Have a way to configure tokens for expiry in POST request
Authenticate endpoint, add param to set expiry in seconds.  Makes testing easier.

### PR DESCRIPTION
**Pull request by ajres**
fixes #1847

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1873)

### CODE REVIEW

**Comment by tleyden** [comment]
The unit tests failed with this error:

https://gist.github.com/tleyden/4d6ae597c0d0cbb5f5a6f156a59ff4a7

Going to re-run

**Comment by tleyden** [comment]
Re-running, failed with the same error.  @ajres can you run the full test suite locally and see if it's passing for you?

You can see the test params here: https://github.com/couchbase/sync_gateway/blob/master/.drone.yml

```
./test.sh -race -cpu 4
```

**Comment by tleyden** [comment]
It doesn't look like the unit test failure could have anything to do with this change though .. I wonder if we should just merge it?  @adamcfraser any thoughts?

**Comment by adamcfraser** [comment]
I haven't seen that failure running locally.  It looks like the usual 'bucket is closed before db is stopped' error.  In any case it looks unrelated to this change - I think it's ok to merge.

**Pull request merged**
