### PR TITLE
Fixes #1888 Make HTTP/2 support opt-in

### LINKED ISSUE #1888: Make HTTP/2 support opt-in
Based on issues found when running the current iOS unit tests w/ HTTP/2 (https://github.com/couchbase/couchbase-lite-ios/issues/1307), we should make HTTP/2 support opt-in on the Sync Gateway side for release 1.3.  

I think it makes sense to do this by moving it to an 'unsupported' config option, since we haven't successfully tested/validated.  Once we've done more internal validation of HTTP/2, we can enable it by default (possibly with an opt-out option).

### PR DESCRIPTION
**Pull request by tleyden**
This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1894)

### CODE REVIEW

**Comment by tleyden** [comment]
Fixes #1888

**Comment by adamcfraser** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[examples/ssl/ssl.json, line 1 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894#-KKoo68OYx1h61xno9bb:-KKoo68OYx1h61xno9bc:1201613362) ([raw file](https://github.com/couchbase/sync_gateway/blob/bd863e267c86cf5d3b5aea636c8f5912734253ba/examples/ssl/ssl.json#L1)):_

> ``` JSON
> {
> ```

I'm not sure this formatting is an improvement?  But can leave in place if it's intentional.

---

_[rest/config.go, line 614 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894#-KKonuiIqr0nuc7JQ6HL:-KKonuiJISv8N4tPKQqk:2084369632) ([raw file](https://github.com/couchbase/sync_gateway/blob/bd863e267c86cf5d3b5aea636c8f5912734253ba/rest/config.go#L614)):_

> ``` Go
> 
>   http2Enabled := false
>   if config.Unsupported != nil {
> ```

Looks like this should also check for Unsupported.Http2Config != nil?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894)_

**Comment by tleyden** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[examples/ssl/ssl.json, line 1 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894#-KKoo68OYx1h61xno9bb:-KKor2HPatSKmyriHBKK:887862525) ([raw file](https://github.com/couchbase/sync_gateway/blob/bd863e267c86cf5d3b5aea636c8f5912734253ba/examples/ssl/ssl.json#L1)):_
<details><summary>

<i>Previously, adamcfraser (Adam Fraser) wrote…</i></summary>



> I'm not sure this formatting is an improvement?  But can leave in place if it's intentional.
> </details>
> Yeah it's intentional, I just used the standard json formatting tool: https://jsonformatter.curiousconcept.com/ to fix the indentation when adding logs = *

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894)_

**Comment by tleyden** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[rest/config.go, line 614 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894#-KKonuiIqr0nuc7JQ6HL:-KKorGmLPdFcsfCbRTBI:-499146009) ([raw file](https://github.com/couchbase/sync_gateway/blob/bd863e267c86cf5d3b5aea636c8f5912734253ba/rest/config.go#L614)):_
<details><summary>

<i>Previously, adamcfraser (Adam Fraser) wrote…</i></summary>



> Looks like this should also check for Unsupported.Http2Config != nil?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894)_

**Comment by adamcfraser** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1894)_

**Pull request merged**
