### PR TITLE
Bump sg-replicate to include changes limit fix -- blocked on functional tests

### PR DESCRIPTION
**Pull request by sethrosetter**

### CODE REVIEW

**Comment by tleyden** [comment]
Func test in progress:

http://uberjenkins.sc.couchbase.com/view/QE%20Dev/job/syncgateway-functional-tests-dev/188/console

**Comment by tleyden** [comment]
This func test failed, but I'm not sure why:

http://uberjenkins.sc.couchbase.com/job/centos7-mobile-sync-gateway-functional-tests/99/

@sethrosetter any idea?

**Comment by sethrosetter** [comment]
Tests ran but timed out on an sg_replicate functional test. Need to investigate - http://uberjenkins.sc.couchbase.com/job/centos7-mobile-sync-gateway-functional-tests/101/console

**Comment by tleyden** [comment]
@sethrosetter could not reproduce the functional test failure locally by running:

```
pytest -s --server-version=4.5.0 --sync-gateway-version=5aac91c8b98252449336b01aa392d6c3001d39a9 testsuites/syncgateway/functional/2sg_1cbs/test_sg_replicate.py
```

Output:

```
      TEARDOWN F setup_2sg_1cbs_testUnsetting CLUSTER_CONFIG
Tearing down 'setup_2sg_1cbs_suite' ...

  TEARDOWN M setup_2sg_1cbs_suite
 testsuites/syncgateway/functional/2sg_1cbs/test_sg_replicate.pytest_replication_config ✓                        100% ██████████
---------------------- generated xml file: /Users/tleyden/Development/mobile-testkit/results/results.xml -----------------------
---------------------- generated html file: /Users/tleyden/Development/mobile-testkit/results/report.html ----------------------

Results (486.46s):
       8 passed
```

screen shot 2016-11-15 at 5 38 17 pm

**Comment by tleyden** [comment]
I re-ran locally and got same result

**Comment by tleyden** [comment]
The test passed on Jenkins as well: http://uberjenkins.sc.couchbase.com/job/centos7-mobile-sync-gateway-functional-tests/127/

**Pull request merged**
