### PR TITLE
PR: Improve developer workflow with revamped snap-manifest script

### PR DESCRIPTION
**Pull request by tleyden**
Fixes https://github.com/couchbase/sync_gateway/issues/2445

### CODE REVIEW

**Comment by tleyden** [comment]
Here is a sample run.

## Initial state

I'm currently have my sync gateway repo on the `feature/fix_snap_manifest_rebased` branch and walrus is on `feature/sg_2418_sgbucket_interface`:

```
$ repo status
project godeps/src/github.com/couchbase/sync_gateway/ branch feature/fix_snap_manifest_rebased
project godeps/src/github.com/couchbaselabs/sync-gateway-accel/ branch master
project godeps/src/github.com/couchbaselabs/walrus/ branch feature/sg_2418_sgbucket_interface
```

I want to switch everything over to be on the `feature/sg_2418_sgbucket_interface` branch, which has the latest commit of 36ad67135145f352c0bb284ac99a2c15688e44d8 (which is pushed up to github already, which is required when running the updated version of snap-manifest.sh)

## Run snap-manifest.sh to switch to commit

```
$ ./snap-manifest.sh 36ad67135145f352c0bb284ac99a2c15688e44d8
```

Output: https://gist.github.com/tleyden/f29f11db8ef58252923aec6b8f27e186

Now the `repo status` output is clean:

```
$ repo status
nothing to commit (working directory clean)
```

and `repo info` shows [detailed output of each repository commit](https://gist.github.com/tleyden/2076c4aa7428ec9949434dba9e408884) 



## Run snap-manifest.sh to switch back to master

```
./snap-manifest 48aa474df49a58b591e3a6a6d55dee094af65a13
```

Output: https://gist.github.com/tleyden/eb488751db17a781df5fc865861c7445

`repo status` shows `nothing to commit (working directory clean)`

`repo info` shows [detailed output of each respository commit](https://gist.github.com/tleyden/170f466670f38f3612ea18624a72b951) 


## Run snap-manifest.sh to switch to `release/1.4.0.2` branch

```
$ ./snap-manifest.sh 8fa08fb27b19c1b6a0ccb86a27c3b91b7fb806d8
```

Output: https://gist.github.com/tleyden/512b03b7afba757d10e5b2cae0a8182c

`repo info` [detailed output of each repository commit](https://gist.github.com/tleyden/9092630d0c0c38b0d2f7a250756f2378) .  

Note in the `repo info` output that now the `go-blip` repo is no longer in the list, since that was added to the master branch after the `1.4.0.0` tag was created, which is what the `release/1.4.0.2` branch is based off of

**Comment by adamcfraser** [comment]
From the description, I'm assuming it's a hard requirement to have pushed the updated manifest you want to use to github?

**Comment by tleyden** [comment]
It's just a hard requirement that the commit you are trying to "snap to" is on github.  Since all commits have a manifest/default.xml file, then it can download the manifest/default.xml corresponding to that commit

**Comment by tleyden** [comment]
@ajres I added a few more commits per conversation on hipchat .. new usage:

```
    ./snap-manifest --sg-commit <commit-hash>

    or

    ./snap-manifest --sg-commit <commit-hash> --local-manifest /path/to/sg/repo/manifest/default.xml
```

**Comment by ajres** [comment]
Been running with this for 24 hours, no issues so far checking out different branches and snapping to branch manifest.

**Pull request merged**
