### PR TITLE
Add OpenID Connect authentication

### LINKED ISSUE #1688: Implement OpenID Connect relying-party support
As an application architect, I want Sync Gateway to be able to use my existing SSO infrastructure so that I only need to maintain a single database of users identities and the resources that they have authorization to access, reducing both time-to-market and administrative overhead.

### PR DESCRIPTION
**Pull request by adamcfraser**
Fixes #1688

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/1830)

### CODE REVIEW

**Comment by ajres** [comment]
_[auth/auth.go, line 300 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfS5VholhJSEcBrq16:-KJfS5VholhJSEcBrq17:1057027151) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/auth/auth.go#L300)):_

> ``` Go
>       return nil, jose.JWT{}, err
>   }
>   var provider *OIDCProvider
> ```

I created the following method in oidc.go, that could be used here.

`func (opm OIDCProviderMap) GetProviderForIssuer(issuer string) (*OIDCProvider)`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830)_

**Comment by ajres** [comment]
_[rest/oidc_api.go, line 118 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfVHuVXHAe16AyB_yk:-KJfVHuVXHAe16AyB_yl:1831369306) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_api.go#L118)):_

> ``` Go
>   }
> 
>   oac, err := provider.GetClient().OAuthClient()
> ```

The call to OAuthClient will panic if the client_id or validation_key are missing from the provider config. We should probably add some validation when parsing the oidc provider config.

2016-06-07 16:31:24.253319 I | http: panic serving [::1]:56737: runtime error: invalid memory address or nil pointer dereference
goroutine 100 [running]:
net/http.(_conn).serve.func1(0xc8200c82c0, 0x63ac600, 0xc8201ec418)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/coreos/go-oidc/oidc.(_Client).OAuthClient(0x0, 0x0, 0x0, 0x0)
    /Users/andy/projects/sync_gateway/godeps/src/github.com/coreos/go-oidc/oidc/client.go:626 +0x3c
github.com/couchbase/sync_gateway/rest.(_handler).handleOIDCCallback(0xc820b36510, 0x0, 0x0)
    /Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/oidc_api.go:118 +0x3cc
github.com/couchbase/sync_gateway/rest.(_handler).invoke(0xc820b36510, 0x4b4f150, 0x0, 0x0)
    /Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:200 +0x7b4

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830)_

**Comment by ajres** [comment]
_[rest/oidc_test_provider.go, line 30 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfWVXWEvOBwKWNF9dw:-KJfWVXWEvOBwKWNF9dx:-1688864789) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_test_provider.go#L30)):_

> ``` Go
> This provider is enabled per database by adding the following database proeprties to the Sync Gateway config
> <pre>
> "oidc": {
> ```

This needs to be updated to the new config format for multiple providers

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830)_

**Comment by ajres** [comment]
_[rest/oidc_test_provider.go, line 73 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfWgId4iGEm_kw8qnI:-KJfWgId4iGEm_kw8qnJ:-1877817059) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_test_provider.go#L73)):_

> ``` Go
> }
> 
> type AuthState struct {
> ```

We're not using all the struct properties at the moment either remove unused, or implement more of the request validation requirements from the OIDC spec

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830)_

**Comment by ajres** [comment]
_[rest/oidc_test_provider.go, line 365 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfXVGMkGaA71zoJswF:-KJfXVGNlIK8i7NmTu1E:920447156) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_test_provider.go#L365)):_

> ``` Go
> 
>   tokenResponse := &OidcTokenResponse{
>       AccessToken:  accessToken,
> ```

We're always returning an Access Token, I don't think this is strictly per the OIDC spec, do we need to implement the full spec logic here?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830)_

**Comment by adamcfraser** [comment]
Reviewed 3 of 12 files at r2, 3 of 7 files at r5, 2 of 4 files at r6, 1 of 2 files at r8, 2 of 4 files at r10, 1 of 2 files at r12, 3 of 3 files at r13.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[auth/auth.go, line 300 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfS5VholhJSEcBrq16:-KJw7meWOj4vSDlBLmDp:929863281) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/auth/auth.go#L300)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> I created the following method in oidc.go, that could be used here.
> 
> `func (opm OIDCProviderMap) GetProviderForIssuer(issuer string) (*OIDCProvider)`
> </details>
> Good call - I've updated to use that method.

---

_[manifest/default.xml, line 19 [r12]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJwCPvlzJ6hOX62UfSJ:-KJwCPvmP_bW2ytdnU-r:-829257129) ([raw file](https://github.com/couchbase/sync_gateway/blob/94d2ea4b5f79e01a10f637942cc675b1951fb31b/manifest/default.xml#L19)):_

> ``` XML
>   <remote fetch="ssh://github.com/couchbaselabs/" name="couchbaselabs_private"/>
>   <remote fetch="git://github.com/coreos/" name="coreos"/>
> 
> ```

Duplicate entry here - will remove.

---

_[rest/oidc_api.go, line 118 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfVHuVXHAe16AyB_yk:-KJhCg7HhemuGpvlWtrr:1956035264) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_api.go#L118)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> The call to OAuthClient will panic if the client_id or validation_key are missing from the provider config. We should probably add some validation when parsing the oidc provider config.
> 
> 2016-06-07 16:31:24.253319 I | http: panic serving [::1]:56737: runtime error: invalid memory address or nil pointer dereference
> goroutine 100 [running]:
> net/http.(_conn).serve.func1(0xc8200c82c0, 0x63ac600, 0xc8201ec418)
>   /usr/local/go/src/net/http/server.go:1287 +0xb5
> github.com/coreos/go-oidc/oidc.(_Client).OAuthClient(0x0, 0x0, 0x0, 0x0)
>   /Users/andy/projects/sync_gateway/godeps/src/github.com/coreos/go-oidc/oidc/client.go:626 +0x3c
> github.com/couchbase/sync_gateway/rest.(_handler).handleOIDCCallback(0xc820b36510, 0x0, 0x0)
>   /Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/oidc_api.go:118 +0x3cc
> github.com/couchbase/sync_gateway/rest.(_handler).invoke(0xc820b36510, 0x4b4f150, 0x0, 0x0)
>   /Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:200 +0x7b4
> 
> </details>
> Agree - added validation for required provider fields, and check for at least one valid provider.

---

_[rest/oidc_test_provider.go, line 30 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfWVXWEvOBwKWNF9dw:-KJhDLFJvmib4mzqXH9U:-1705128026) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_test_provider.go#L30)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> This needs to be updated to the new config format for multiple providers
> </details>
> Not sure if this was intended for me or you, but I've updated.

---

_[rest/oidc_test_provider.go, line 73 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfWgId4iGEm_kw8qnI:-KJwLKGSPrb0lggB2Vqo:380217413) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_test_provider.go#L73)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> We're not using all the struct properties at the moment either remove unused, or implement more of the request validation requirements from the OIDC spec
> </details>
> I think it's fine to leave them in place for future usage, although could add 'omitempty' at some point.

---

_[rest/oidc_test_provider.go, line 365 [r7]](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830#-KJfXVGMkGaA71zoJswF:-KJhDg19P-4JF_5jUjc8:1581337227) ([raw file](https://github.com/couchbase/sync_gateway/blob/34beb844a21869f577b038c8d2ab77f3550709bd/rest/oidc_test_provider.go#L365)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> We're always returning an Access Token, I don't think this is strictly per the OIDC spec, do we need to implement the full spec logic here?
> </details>
> Probably not critical since we're not using Access Tokens anywhere - could leave it in.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/1830)_

**Comment by adamcfraser** [comment]
Data race in the CI build looks unrelated to this PR (it's offline/online) - merging.

**Pull request merged**
