### PR TITLE
Adds a configuration option to prevent sending of WWW-Authenticate header

### PR DESCRIPTION
**Pull request by mz2**
Adds an optional configuration flag to optionally omit the inclusion of a WWW-Authenticate header in authentication error cases. The default behaviour is unchanged.

This is made necessary by the fixed behaviour of browsers on encountering WWW-Authenticate (https://stackoverflow.com/a/37919017/504931), which is not compatible with the use of Sync Gateway from a web browser client (auth popup is not something we want on hitting for example an expired session cookie – will want our own clientside logic to handle that case).

### CODE REVIEW

**Comment by adamcfraser** [comment]
Thanks for the submission.  This looks like a reasonable enhancement, but I think it might make more sense as a database-level config, instead of server, since auth is db-specific.

**Comment by mz2** [comment]
Ah, good one, I agree. @will118, this should be a simple change, right?

**Comment by will118** [comment]
Yeah this makes sense. I’ll give it a go.

**Comment by will118** [comment]
I've pushed some commits (which hopefully we can squash) that moves the config to the database/bucket level.

```
{
  "log": [ "CRUD+", "HTTP+", "REST+", "Changes+", "Attach+" ],
  "interface": ":4984",
  "adminInterface": ":4985",
  "databases": {
    "user_bucket": {
      "server": "http://localhost:8091",
      "send_www_authenticate_header": false,
      "password": "foobarbaz"
    }
  }
}
```

I'm open to renaming the flag.

p.s. unfortunately the diff is largely indentation changes.

**Comment by adamcfraser** [comment]
Looks good, thanks.  It looks like @mz2 has already signed the Couchbase CLA - thanks for that as well.

I've pushed a copy to local branch mpapp-feature/www-authenticate-optional to sanity check w/ integration tests.  Will merge after that completes.

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/471/

**Comment by mz2** [comment]
@adamcfraser actually the changes were by @will118 who I'm sure is happy to sign the CLA too, I just opened the fork we keep of Sync Gateway for the https://manuscriptsapp.com team purely for the purposes of this configurability change, and opened the pull request.

**Comment by will118** [comment]
@adamcfraser I've just signed it, let me know if there are any issues.

**Comment by adamcfraser** [comment]
@will118 Details on how to sign the CLA are here:
https://developer.couchbase.com/open-source-projects/#how-to-contribute-code

Let me know once you've signed - thanks!

**Comment by adamcfraser** [comment]
@will118 Thanks - looks good.

**Comment by adamcfraser** [comment]
Integration test issues are unrelated to this PR - will merge.  Thanks again for the submission.

**Comment by stemail23** [comment]
So I just sat down to investigate a solution to this myself, and discovered that it was already recently implemented here! Is there any chance this can be included in a v1.5.x SyncGateway release, or do we have to wait for v2? We urgently need this behaviour in an upcoming release, and we're not in a position to migrate to SyncGateway v2.0 at this stage.

**Comment by adamcfraser** [comment]
@stemail23 We don't currently have a 1.5.x scheduled, and on its own I don't think this enhancement merits a maintenance release.  If you've got a support contract you could try to escalate through that channel.

**Pull request merged**
