### PR TITLE
Feature/issue 2004 sgcollect info logs

### PR DESCRIPTION
**Pull request by tleyden**
Fixes https://github.com/couchbase/sync_gateway/issues/2004

---

This change is [Reviewable](https://reviewable.io/reviews/couchbase/sync_gateway/2006)

### CODE REVIEW

**Comment by ajres** [comment]
_[tools/sgcollect_info, line 214 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/2006#-KNgwp3poZRz1pdhH2vA:-KNgwp3poZRz1pdhH2vB:101360644) ([raw file](https://github.com/couchbase/sync_gateway/blob/b3fe055ae3df828e41de67fcb236e38951eca729/tools/sgcollect_info#L214)):_

> ```
>         "/Users/sync_gateway/logs",
>         "/Users/sg_accel/logs",
>         R'C:\Program Files (x86)\Couchbase\var\lib\couchbase'
> ```

If we appended '\logs' to the winodws path, couldn't we remove the "windows_sg_error.log" and  "windows_sa_error.log" entries above?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2006)_

**Comment by tleyden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[tools/sgcollect_info, line 214 [r1]](https://reviewable.io:443/reviews/couchbase/sync_gateway/2006#-KNgwp3poZRz1pdhH2vA:-KNhC5NcD75-yeO0NNnd:-499146009) ([raw file](https://github.com/couchbase/sync_gateway/blob/b3fe055ae3df828e41de67fcb236e38951eca729/tools/sgcollect_info#L214)):_
<details><summary>

<i>Previously, ajres (Andrew Reslan) wrote…</i></summary>



> If we appended '\logs' to the winodws path, couldn't we remove the "windows_sg_error.log" and  "windows_sa_error.log" entries above?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2006)_

**Comment by ajres** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2006)_

**Comment by ajres** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/couchbase/sync_gateway/2006#-:-KNhDFj686PNF8TIlN1m:1417088721)_

**Pull request merged**
