### PR TITLE
Fixed #3270 Update tests that wait on waitgroups to have timeout

### LINKED ISSUE #3270: Update tests that wait on waitgroups to have timeout
As reported in https://github.com/couchbase/sync_gateway/issues/3268, the test essentially blocked forever after not getting expected results.

Rather than blocking forever, the test should instead fail with a timeout.  This is a separate issue from the underlying cause of https://github.com/couchbase/sync_gateway/issues/3268, and affects more tests... so I'm spinning out a separate issue / PR for this

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #3270 

Times out test after 1 minute rather than blocking indefinitely on waitgroup

### CODE REVIEW

**Comment by tleyden** [comment]
Integration tests: (single test)

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/368/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/369/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/370/

**Review by adamcfraser — APPROVED** [review]
Looks good.  

Any interest in fixing the typo on recevied in this PR?

**Comment by tleyden** [comment]
After investigating https://github.com/couchbase/sync_gateway/issues/3268 some more, it turns out that the test blocked indefinitely on the call to put the request, which happened *before* the test even got to the waitgroup.

However, this change is still useful for a class of test failures where the revs are all sent to the server, but the test doesn't receive them in a timely manner.

Manually tested by artificially bumping the waitgroup counter and verifying that the waitgroup timeout kicked in to fail the test.

**Comment by tleyden** [comment]
@adamcfraser after the drone ci passes, this should be ready to review/merge

**Comment by tleyden** [comment]
Log snippet for example failing test (artificially induced):

```
2018-02-05T13:56:32.276-08:00 Sync+: [cdbb58a]     Sending 0 changes. User:GUEST
2018-02-05T13:56:32.276-08:00 Sync+: [cdbb58a]     Sending 1 changes. User:GUEST
2018-02-05T13:56:32.277-08:00 Sync: [cdbb58a] Sent 1 changes to client, from seq 1499.  User:GUEST
2018-02-05T13:56:32.277-08:00 Sync+: [cdbb58a]     Sending 0 changes. User:GUEST
	changes_api_test.go:2041: Timed out waiting for all changes.: Timed out waiting after 10s

Process finished with exit code 1
```

**Review by bbrks — APPROVED** [review]

**Pull request merged**
